// Package deadman implements the out-of-band rollback subsystem described
// in specs/deadman/timer.spec.yaml.
//
// When the engine must apply a control-channel-affecting change — one that
// could disrupt the SSH connection that Kensa is using — it arms a deadman
// timer before apply. If the control channel survives apply+validate, the
// engine cancels the timer. If the connection is lost mid-apply, the
// scheduled script fires autonomously on the target host and restores
// pre-capture state.
//
// # Scheduler support
//
// The armer probes the host for at(1) or systemd-run. If neither is
// available the engine returns [api.ErrSchedulerUnavailable] and refuses
// to execute the rule (deadman-timer spec C-01).
//
// # Script generation
//
// The rollback script is generated by dry-running each capturable step's
// [api.RollbackHandler] against a [recordingTransport] that records the
// shell commands without executing them. The commands are written into a
// self-contained POSIX sh script (deadman-timer spec C-02) that removes
// itself on exit (C-05).
//
// # Cancellation
//
// [Armer.Cancel] removes the scheduled job, removes the script file, then
// verifies the job is gone (deadman-timer spec C-04, AC-05).
package deadman

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"

	"github.com/Hanalyx/kensa-go/api"
	"github.com/Hanalyx/kensa-go/internal/handler"
)

// defaultWindow is the minimum timer window per deadman-timer spec C-03.
const defaultWindow = 120 * time.Second

// schedulerKind identifies which scheduler was detected on the host.
type schedulerKind string

const (
	schedulerAt         schedulerKind = "at"
	schedulerSystemdRun schedulerKind = "systemd-run"
)

// armedJob holds the state for one armed deadman timer.
type armedJob struct {
	scheduler  schedulerKind
	jobID      string // at: numeric job ID; systemd-run: unit name
	scriptPath string
	firesAt    int64
}

// Armer is the production DeadmanArmer. Construct with [New].
//
// Armer satisfies the engine's [engine.DeadmanArmer] interface. Callers
// should use [engine.WithDeadman] to inject it into an [engine.Engine]:
//
//	eng := engine.New(engine.WithDeadman(deadman.New(0, nil)))
type Armer struct {
	window   time.Duration
	registry *handler.Registry

	mu   sync.Mutex
	jobs map[uuid.UUID]*armedJob
}

// New returns an Armer with the given timer window. Pass 0 to use the
// default 120-second window (deadman-timer spec C-03). Pass nil for
// registry to use [handler.Default].
func New(window time.Duration, registry *handler.Registry) *Armer {
	if window <= 0 {
		window = defaultWindow
	}
	if registry == nil {
		registry = handler.Default()
	}
	return &Armer{
		window:   window,
		registry: registry,
		jobs:     make(map[uuid.UUID]*armedJob),
	}
}

// Arm implements engine.DeadmanArmer.
//
// It probes for a scheduler, dry-runs each capturable step's rollback
// handler to collect shell commands, generates a POSIX shell script,
// uploads it to /tmp/kensa-rollback-<txn-id>.sh, schedules it, and
// verifies the job appears in the scheduler's queue.
//
// Failure modes:
//   - Neither at(1) nor systemd-run available → [api.ErrSchedulerUnavailable].
//   - Rollback dry-run fails (unknown mechanism) → typed error.
//   - Script upload fails (disk full, permissions) → typed error; no
//     apply will run because the engine fails on Arm error.
//   - Post-schedule verification fails → typed error; script file is
//     removed before returning.
func (a *Armer) Arm(ctx context.Context, transport api.Transport, txnID uuid.UUID, preStates []api.PreState) (string, int64, error) {
	// @spec deadman-timer
	// @ac AC-01 — detect scheduler availability.
	sched, err := detectScheduler(ctx, transport)
	if err != nil {
		return "", 0, api.ErrSchedulerUnavailable
	}

	// @ac AC-02 — generate rollback commands via dry-run.
	cmds, err := a.collectRollbackCommands(preStates)
	if err != nil {
		return "", 0, fmt.Errorf("deadman: build rollback commands: %w", err)
	}

	scriptPath := fmt.Sprintf("/tmp/kensa-rollback-%s.sh", txnID)
	scriptContent := buildScript(txnID, cmds)

	// @ac AC-03 — upload script to /tmp/kensa-rollback-<txn-id>.sh mode 0700.
	if err := uploadScript(ctx, transport, scriptContent, scriptPath); err != nil {
		return "", 0, fmt.Errorf("deadman: upload rollback script: %w", err)
	}

	// @ac AC-04 — schedule via at or systemd-run and verify.
	firesAt := time.Now().Add(a.window).Unix()
	jobID, err := schedule(ctx, transport, sched, txnID, scriptPath, a.window)
	if err != nil {
		// Clean up the orphaned script file before returning.
		_, _ = transport.Run(ctx, "rm -f "+shellQuote(scriptPath))
		return "", 0, fmt.Errorf("deadman: schedule: %w", err)
	}

	a.mu.Lock()
	a.jobs[txnID] = &armedJob{
		scheduler:  sched,
		jobID:      jobID,
		scriptPath: scriptPath,
		firesAt:    firesAt,
	}
	a.mu.Unlock()

	return scriptPath, firesAt, nil
}

// Cancel implements engine.DeadmanArmer.
//
// It removes the scheduled job, removes the script file, and verifies
// the job is no longer present in the scheduler's queue (deadman-timer
// spec C-04, AC-05, C-05, AC-08).
//
// Returns [api.ErrNoActiveDeadman] when no timer is armed for txnID.
//
// Failure modes:
//   - atrm/systemctl fails → typed error; the deadman may still fire.
//   - Post-cancel verification shows job still present → typed error.
//   - Script rm fails → logged anomaly but does not fail the cancel;
//     residual files are hygiene failures per spec C-05.
func (a *Armer) Cancel(ctx context.Context, transport api.Transport, txnID uuid.UUID) error {
	a.mu.Lock()
	job, ok := a.jobs[txnID]
	if !ok {
		a.mu.Unlock()
		return api.ErrNoActiveDeadman
	}
	delete(a.jobs, txnID)
	a.mu.Unlock()

	// @ac AC-05 — cancel scheduled job and verify.
	if err := cancelJob(ctx, transport, job); err != nil {
		return err
	}

	// @ac AC-08 — remove script file.
	_, _ = transport.Run(ctx, "rm -f "+shellQuote(job.scriptPath))

	return nil
}

// detectScheduler probes the target host for at(1) or systemd-run.
// Returns [schedulerAt] or [schedulerSystemdRun] on success.
// Returns a non-nil error (which [Arm] converts to [api.ErrSchedulerUnavailable])
// when neither is found.
func detectScheduler(ctx context.Context, transport api.Transport) (schedulerKind, error) {
	// Prefer at(1): universally available on RHEL via the at/cronie package.
	res, err := transport.Run(ctx, "command -v at 2>/dev/null && echo __AT_FOUND__ || true")
	if err == nil && strings.Contains(res.Stdout, "__AT_FOUND__") {
		return schedulerAt, nil
	}
	// Fall back to systemd-run (RHEL 7+).
	res, err = transport.Run(ctx, "command -v systemd-run 2>/dev/null && echo __SDR_FOUND__ || true")
	if err == nil && strings.Contains(res.Stdout, "__SDR_FOUND__") {
		return schedulerSystemdRun, nil
	}
	return "", errors.New("deadman: no scheduler found")
}

// collectRollbackCommands dry-runs each capturable step's rollback handler
// using a [recordingTransport] and returns the shell commands in rollback
// execution order (reverse of apply order, per deadman-timer spec AC-02).
func (a *Armer) collectRollbackCommands(preStates []api.PreState) ([]string, error) {
	rec := &recordingTransport{}
	ctx := context.Background()

	for i := len(preStates) - 1; i >= 0; i-- {
		ps := preStates[i]
		if !ps.Capturable {
			continue
		}
		h, ok := a.registry.Get(ps.Mechanism)
		if !ok {
			return nil, fmt.Errorf("unknown mechanism %q", ps.Mechanism)
		}
		rh, ok := h.(api.RollbackHandler)
		if !ok {
			return nil, fmt.Errorf("mechanism %q does not implement RollbackHandler", ps.Mechanism)
		}
		pre := ps
		if _, err := rh.Rollback(ctx, rec, &pre); err != nil {
			return nil, fmt.Errorf("dry-run rollback step %d (%s): %w", ps.StepIndex, ps.Mechanism, err)
		}
	}
	return rec.cmds, nil
}

// buildScript generates a self-contained POSIX sh rollback script.
// The script runs cmds in order (already in reverse-apply order)
// and removes itself on exit (deadman-timer spec C-05).
func buildScript(txnID uuid.UUID, cmds []string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Kensa deadman rollback script\n")
	b.WriteString(fmt.Sprintf("# Transaction:  %s\n", txnID))
	b.WriteString(fmt.Sprintf("# Generated at: %s\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString("# This script fires if Kensa loses its control-channel connection\n")
	b.WriteString("# after apply. It restores the pre-apply state captured before any\n")
	b.WriteString("# changes ran. Self-deletes on exit per deadman-timer spec C-05.\n")
	b.WriteString("set -eu\n")
	b.WriteString("cleanup() { rm -f \"$0\"; }\n")
	b.WriteString("trap cleanup EXIT\n")
	b.WriteString("\n")
	for i, cmd := range cmds {
		b.WriteString(fmt.Sprintf("# rollback step %d\n", i+1))
		b.WriteString(cmd)
		b.WriteString("\n")
	}
	return b.String()
}

// uploadScript writes content to remotePath on the host with mode 0700.
// Uses printf to write the content via the control-channel Run path
// (avoids scp and local temp files).
func uploadScript(ctx context.Context, transport api.Transport, content, remotePath string) error {
	// Use printf with single-quoted content (shellQuote handles embedded
	// single quotes via the standard '\''-escape idiom).
	cmd := fmt.Sprintf("printf '%%s' %s > %s && chmod 0700 %s",
		shellQuote(content), shellQuote(remotePath), shellQuote(remotePath),
	)
	res, err := transport.Run(ctx, cmd)
	if err != nil {
		return err
	}
	if !res.OK() {
		return fmt.Errorf("upload failed (exit %d): %s", res.ExitCode, res.Stderr)
	}
	return nil
}

// schedule submits the rollback script for deferred execution. Returns the
// job ID (at numeric ID or systemd-run unit name) for cancellation.
func schedule(ctx context.Context, transport api.Transport, sched schedulerKind, txnID uuid.UUID, scriptPath string, window time.Duration) (string, error) {
	windowSec := int(window.Seconds())
	switch sched {
	case schedulerAt:
		return scheduleAt(ctx, transport, scriptPath, windowSec)
	case schedulerSystemdRun:
		return scheduleSystemdRun(ctx, transport, txnID, scriptPath, windowSec)
	}
	return "", fmt.Errorf("deadman: unknown scheduler %q", sched)
}

// scheduleAt submits the script to at(1) and verifies the job appears in atq.
func scheduleAt(ctx context.Context, transport api.Transport, scriptPath string, windowSec int) (string, error) {
	// at(1) reads the command from stdin. We use a shell one-liner to
	// avoid multi-line stdin over the transport.
	cmd := fmt.Sprintf("echo sh %s | at now + %d seconds 2>&1",
		shellQuote(scriptPath), windowSec)
	res, err := transport.Run(ctx, cmd)
	if err != nil {
		return "", err
	}
	// at(1) exit code is 0 on success but may emit the job summary to stderr.
	combined := res.Stdout + "\n" + res.Stderr
	jobID := extractAtJobID(combined)
	if jobID == "" {
		return "", fmt.Errorf("deadman: could not parse at job ID from output: %q", combined)
	}
	// @ac AC-04 — post-schedule verification.
	if err := verifyAtJobPresent(ctx, transport, jobID); err != nil {
		return "", err
	}
	return jobID, nil
}

// scheduleSystemdRun submits the script via systemd-run and verifies
// the transient timer unit appears in systemctl list-timers.
func scheduleSystemdRun(ctx context.Context, transport api.Transport, txnID uuid.UUID, scriptPath string, windowSec int) (string, error) {
	unitName := fmt.Sprintf("kensa-rollback-%s", txnID)
	cmd := fmt.Sprintf("systemd-run --unit=%s --on-active=%d -- sh %s",
		shellQuote(unitName), windowSec, shellQuote(scriptPath))
	res, err := transport.Run(ctx, cmd)
	if err != nil {
		return "", err
	}
	if !res.OK() {
		return "", fmt.Errorf("deadman: systemd-run failed (exit %d): %s", res.ExitCode, res.Stderr)
	}
	// @ac AC-04 — post-schedule verification.
	if err := verifySystemdUnitPresent(ctx, transport, unitName); err != nil {
		return "", err
	}
	return unitName, nil
}

// cancelJob removes the scheduled job via atrm or systemctl stop and
// verifies the job is gone (deadman-timer spec AC-05).
func cancelJob(ctx context.Context, transport api.Transport, job *armedJob) error {
	switch job.scheduler {
	case schedulerAt:
		res, err := transport.Run(ctx, "atrm "+shellQuote(job.jobID))
		if err != nil {
			return fmt.Errorf("deadman: atrm: %w", err)
		}
		if !res.OK() {
			return fmt.Errorf("deadman: atrm failed (exit %d): %s", res.ExitCode, res.Stderr)
		}
		return verifyAtJobGone(ctx, transport, job.jobID)

	case schedulerSystemdRun:
		// Try both .timer and bare unit name; ignore errors (unit may have
		// already fired or the name variant differs).
		stopCmd := fmt.Sprintf(
			"systemctl stop %s.timer 2>/dev/null; systemctl stop %s 2>/dev/null; true",
			shellQuote(job.jobID), shellQuote(job.jobID),
		)
		if _, err := transport.Run(ctx, stopCmd); err != nil {
			return fmt.Errorf("deadman: systemctl stop: %w", err)
		}
		return verifySystemdUnitGone(ctx, transport, job.jobID)
	}
	return fmt.Errorf("deadman: unknown scheduler %q", job.scheduler)
}

// verifyAtJobPresent confirms jobID appears in atq output.
func verifyAtJobPresent(ctx context.Context, transport api.Transport, jobID string) error {
	res, err := transport.Run(ctx, "atq 2>/dev/null")
	if err != nil {
		return fmt.Errorf("deadman: atq check: %w", err)
	}
	if !strings.Contains(res.Stdout, jobID) {
		return fmt.Errorf("deadman: job %s not found in atq after scheduling", jobID)
	}
	return nil
}

// verifyAtJobGone confirms jobID is absent from atq output.
func verifyAtJobGone(ctx context.Context, transport api.Transport, jobID string) error {
	res, err := transport.Run(ctx, "atq 2>/dev/null")
	if err != nil {
		return fmt.Errorf("deadman: atq check after cancel: %w", err)
	}
	// Match "7\t" (tab-delimited atq format) to avoid prefix-matching job 70.
	if strings.Contains(res.Stdout, jobID+"\t") {
		return fmt.Errorf("deadman: job %s still present in atq after cancel", jobID)
	}
	return nil
}

// verifySystemdUnitPresent confirms the transient timer unit appears active.
func verifySystemdUnitPresent(ctx context.Context, transport api.Transport, unitName string) error {
	res, err := transport.Run(ctx, fmt.Sprintf(
		"systemctl show -p LoadState --value %s.timer 2>/dev/null || true",
		shellQuote(unitName),
	))
	if err != nil {
		return fmt.Errorf("deadman: systemctl show after schedule: %w", err)
	}
	state := strings.TrimSpace(res.Stdout)
	if state == "not-found" || state == "" {
		return fmt.Errorf("deadman: unit %s.timer not found after scheduling", unitName)
	}
	return nil
}

// verifySystemdUnitGone confirms the transient timer unit is no longer active.
func verifySystemdUnitGone(ctx context.Context, transport api.Transport, unitName string) error {
	res, err := transport.Run(ctx, fmt.Sprintf(
		"systemctl is-active %s.timer 2>/dev/null; true",
		shellQuote(unitName),
	))
	if err != nil {
		// Transport error — can't verify. Don't fail the cancel.
		return nil
	}
	if strings.TrimSpace(res.Stdout) == "active" {
		return fmt.Errorf("deadman: unit %s.timer still active after cancel", unitName)
	}
	return nil
}

// Job number extraction helper for at(1) scheduling.
// At(1) writes "job N at <date>" to stderr (POSIX) or stdout (some implementations);
// extractAtJobID returns the numeric job ID from that output.
func extractAtJobID(output string) string {
	for _, line := range strings.Split(output, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "job ") {
			fields := strings.Fields(line)
			if len(fields) >= 2 {
				return fields[1]
			}
		}
	}
	return ""
}

// recordingTransport implements [api.Transport] for dry-run rollback.
// [Run] records shell commands without executing them. All other
// methods are no-ops so rollback handlers can call them safely.
type recordingTransport struct {
	cmds []string
}

func (r *recordingTransport) Run(_ context.Context, cmd string) (*api.CommandResult, error) {
	r.cmds = append(r.cmds, cmd)
	return &api.CommandResult{ExitCode: 0}, nil
}

func (r *recordingTransport) Put(_ context.Context, _, _ string, _ fs.FileMode) error { return nil }
func (r *recordingTransport) Get(_ context.Context, _, _ string) error                { return nil }
func (r *recordingTransport) Close() error                                            { return nil }
func (r *recordingTransport) ControlChannelSensitive() bool                           { return false }

// shellQuote wraps s in single quotes, escaping embedded single quotes
// via the standard '\”-idiom so the result is safe to embed in a shell
// command string.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// Compile-time assertion: *Armer satisfies the engine.DeadmanArmer interface.
// The interface lives in internal/engine which we cannot import here
// (import cycle), so we assert the method set by signature matching instead.
var _ interface {
	Arm(context.Context, api.Transport, uuid.UUID, []api.PreState) (string, int64, error)
	Cancel(context.Context, api.Transport, uuid.UUID) error
} = (*Armer)(nil)
