package bootguard

import (
	"context"
	"errors"
	"fmt"
	"path"
	"strings"

	"github.com/Hanalyx/kensa/api"
)

// State paths the guard stages on the target. The boot-time revert reads
// these without the controller.
const (
	StateDir         = "/var/lib/kensa/bootguard"
	entriesBakDir    = StateDir + "/entries"
	defaultGrubBak   = StateDir + "/default_grub.bak"
	revertScriptPath = StateDir + "/revert.sh"
)

// StageRevert writes, on the host, everything a boot-time revert needs to
// restore the captured boot state WITHOUT the controller: a backup of each
// captured file plus a self-contained POSIX revert script. The family-specific
// boot marker/hook that actually triggers the script on a failed boot is set
// separately (the RHEL boot_success / Ubuntu recordfail increments).
//
// Why shell, not Go: the target has no kensa binary at boot, so
// bootguard.Restore (Go, controller-side) cannot run there. revert.sh mirrors
// Restore's logic in POSIX shell. StageRevert must run over a privileged
// (Sudo) transport — it writes root-owned state under /var/lib/kensa.
//
// StageRevert is part of the gated #14 mechanism; it does not arm a working
// guard on its own (no marker/hook yet) and must not be wired into a handler
// until the founder ratifies the §7 analysis and the destructive reboot test
// passes.
func StageRevert(ctx context.Context, t api.Transport, snap *Snapshot) error {
	if snap == nil {
		return errors.New("bootguard: StageRevert called with nil snapshot")
	}
	if _, err := runOK(ctx, t, "mkdir -p "+shellQuote(entriesBakDir)); err != nil {
		return err
	}
	if err := writeRemoteFile(ctx, t, defaultGrubBak, snap.DefaultGrub); err != nil {
		return err
	}
	if snap.Flavor == FlavorBLS {
		for entryPath, content := range snap.BLSEntries {
			bak := entriesBakDir + "/" + path.Base(entryPath)
			if err := writeRemoteFile(ctx, t, bak, content); err != nil {
				return err
			}
		}
	}
	if err := writeRemoteFile(ctx, t, revertScriptPath, buildRevertScript(snap)); err != nil {
		return err
	}
	if _, err := runOK(ctx, t, "chmod 0750 "+shellQuote(revertScriptPath)); err != nil {
		return err
	}
	return nil
}

// Disarm removes the staged revert artifacts (used after a confirmed-healthy
// boot, or to cancel an armed guard).
func Disarm(ctx context.Context, t api.Transport) error {
	_, err := runOK(ctx, t, "rm -rf "+shellQuote(StateDir))
	return err
}

// buildRevertScript renders the POSIX revert script for snap's flavor. It
// restores /etc/default/grub from the staged backup, and:
//   - BLS: copies the captured entry files back verbatim and does NOT
//     regenerate (entries are authoritative; grub2-mkconfig would clobber
//     per-entry args — the §10 finding).
//   - legacy: regenerates grub.cfg via update-grub (with a grub-mkconfig
//     fallback), since GRUB_CMDLINE_LINUX is the source.
func buildRevertScript(snap *Snapshot) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# kensa bootguard — boot-time revert to the pre-change boot state.\n")
	b.WriteString("# Generated by bootguard.StageRevert. Boot-time revert is shell, not Go:\n")
	b.WriteString("# the target has no kensa binary at boot.\n")
	b.WriteString("set -eu\n")
	fmt.Fprintf(&b, "cp -f %s /etc/default/grub\n", shellQuote(defaultGrubBak))
	switch snap.Flavor {
	case FlavorBLS:
		// Restore entry files verbatim; do NOT regenerate.
		fmt.Fprintf(&b, "for f in %s/*; do\n", entriesBakDir)
		b.WriteString("  [ -e \"$f\" ] || continue\n")
		b.WriteString("  cp -f \"$f\" \"/boot/loader/entries/$(basename \"$f\")\"\n")
		b.WriteString("done\n")
	case FlavorLegacy:
		if snap.GrubCfgPath != "" {
			fmt.Fprintf(&b, "update-grub 2>/dev/null || grub-mkconfig -o %s\n", shellQuote(snap.GrubCfgPath))
		} else {
			b.WriteString("update-grub\n")
		}
	}
	return b.String()
}

// runOK runs cmd and returns an error if the transport failed or the command
// exited non-zero.
func runOK(ctx context.Context, t api.Transport, cmd string) (*api.CommandResult, error) {
	res, err := t.Run(ctx, cmd)
	if err != nil {
		return nil, fmt.Errorf("bootguard: %q: transport error: %w", cmd, err)
	}
	if !res.OK() {
		return nil, fmt.Errorf("bootguard: %q failed (exit %d): %s", cmd, res.ExitCode, strings.TrimSpace(res.Stderr))
	}
	return res, nil
}
