package bootguard

import (
	"context"
	"fmt"

	"github.com/Hanalyx/kensa/api"
)

const (
	confirmUnitName   = "kensa-bootguard-confirm.service"
	confirmUnitPath   = "/etc/systemd/system/" + confirmUnitName
	confirmScriptPath = StateDir + "/confirm.sh"
)

// InstallConfirmUnit stages the Option-B confirm script and installs a systemd
// oneshot that runs it after a healthy boot (multi-user + network-online). The
// script decides, from /proc/cmdline, whether the trial booted:
//
//   - sentinel present  → the trial booted and reached a healthy state:
//     PROMOTE — make the param permanent on the default entry, drop the trial.
//   - sentinel absent    → the host fell back to the saved default (the trial
//     boot failed): CLEAN UP — remove the trial entry, leave the default.
//
// Ordering the unit after network-online.target is the health gate: a trial
// that panics or never reaches networking won't run this, so the consumed
// one-shot falls back to the saved default. (Known limit, §7.1b: a param that
// breaks networking yet still reaches multi-user could be promoted; a stricter
// operator health check can extend this.)
//
// RHEL/BLS only so far; Ubuntu legacy is a separate increment. Must run over a
// privileged (Sudo) transport.
func InstallConfirmUnit(ctx context.Context, t api.Transport, flavor Flavor) error {
	script, err := buildConfirmScript(flavor)
	if err != nil {
		return err
	}
	if _, err := runOK(ctx, t, "mkdir -p "+shellQuote(StateDir)); err != nil {
		return err
	}
	if err := writeRemoteFile(ctx, t, confirmScriptPath, script); err != nil {
		return err
	}
	if _, err := runOK(ctx, t, "chmod 0750 "+shellQuote(confirmScriptPath)); err != nil {
		return err
	}
	if err := writeRemoteFile(ctx, t, confirmUnitPath, buildConfirmUnit()); err != nil {
		return err
	}
	if _, err := runOK(ctx, t, "systemctl daemon-reload"); err != nil {
		return err
	}
	_, err = runOK(ctx, t, "systemctl enable "+confirmUnitName)
	return err
}

// buildConfirmUnit renders the oneshot unit that runs the confirm script on a
// healthy boot. It is flavor-independent (the script carries the per-family
// logic).
func buildConfirmUnit() string {
	return "[Unit]\n" +
		"Description=kensa bootguard - confirm/promote a one-shot trial boot\n" +
		"After=multi-user.target network-online.target\n" +
		"Wants=network-online.target\n" +
		"\n" +
		"[Service]\n" +
		"Type=oneshot\n" +
		"ExecStart=" + confirmScriptPath + "\n" +
		"\n" +
		"[Install]\n" +
		"WantedBy=multi-user.target\n"
}

// buildConfirmScript renders the per-family promote/clean-up script.
func buildConfirmScript(flavor Flavor) (string, error) {
	switch flavor {
	case FlavorBLS:
		return blsConfirmScript(), nil
	case FlavorLegacy:
		return ubuntuConfirmScript(), nil
	default:
		return "", fmt.Errorf("bootguard: confirm script not implemented for flavor %q", flavor)
	}
}

// blsConfirmScript (RHEL): promote = apply the recorded param to the default
// entry via grubby; remove the trial = delete the specific BLS entry carrying
// the sentinel (NOT grubby --remove-kernel, which would drop every entry for
// that kernel, including the default).
func blsConfirmScript() string {
	return "#!/bin/sh\n" +
		"# kensa bootguard confirm (Option B, BLS/RHEL). Generated by InstallConfirmUnit.\n" +
		"set -u\n" +
		"STATE=" + StateDir + "\n" +
		"[ -f \"$STATE/trial_entry\" ] || exit 0\n" +
		"remove_trial() {\n" +
		"  for f in $(grep -l " + trialSentinel + " /boot/loader/entries/*.conf 2>/dev/null); do\n" +
		"    rm -f \"$f\"\n" +
		"  done\n" +
		"}\n" +
		"if grep -q " + trialSentinel + " /proc/cmdline; then\n" +
		"  # Trial booted and reached a healthy boot: make the param permanent.\n" +
		"  PARAM=$(cat \"$STATE/param_applied\" 2>/dev/null || true)\n" +
		"  [ -n \"$PARAM\" ] && grubby --update-kernel=DEFAULT --args=\"$PARAM\"\n" +
		"  remove_trial\n" +
		"else\n" +
		"  # Fell back to the saved default: the trial boot failed. Drop the trial.\n" +
		"  remove_trial\n" +
		"fi\n" +
		"rm -rf \"$STATE\"\n"
}

// ubuntuConfirmScript (legacy): promote = append the recorded param to
// GRUB_CMDLINE_LINUX in /etc/default/grub so it persists on every entry; clean
// up = remove the /etc/grub.d trial script. Either way update-grub regenerates
// grub.cfg (dropping the trial entry).
func ubuntuConfirmScript() string {
	return "#!/bin/sh\n" +
		"# kensa bootguard confirm (Option B, Ubuntu/legacy). Generated by InstallConfirmUnit.\n" +
		"set -u\n" +
		"STATE=" + StateDir + "\n" +
		"[ -f \"$STATE/trial_entry\" ] || exit 0\n" +
		"remove_trial() {\n" +
		"  rm -f " + ubuntuTrialScript + "\n" +
		"  update-grub\n" +
		"}\n" +
		"if grep -q " + trialSentinel + " /proc/cmdline; then\n" +
		"  # Trial booted and reached a healthy boot: make the param permanent on\n" +
		"  # the default cmdline, then regenerate without the trial.\n" +
		"  PARAM=$(cat \"$STATE/param_applied\" 2>/dev/null || true)\n" +
		"  if [ -n \"$PARAM\" ]; then\n" +
		"    sed -i \"s|^\\(GRUB_CMDLINE_LINUX=\\\"[^\\\"]*\\)\\\"|\\1 $PARAM\\\"|\" /etc/default/grub\n" +
		"  fi\n" +
		"  remove_trial\n" +
		"else\n" +
		"  # Fell back to the saved default: the trial boot failed. Drop the trial.\n" +
		"  remove_trial\n" +
		"fi\n" +
		"rm -rf \"$STATE\"\n"
}
