// Package deadman implements the out-of-band rollback subsystem described
// in specs/deadman/timer.spec.yaml.
//
// When the engine must apply a control-channel-affecting change — one that
// could disrupt the SSH connection that Kensa is using — it arms a deadman
// timer before apply. If the control channel survives apply+validate, the
// engine cancels the timer. If the connection is lost mid-apply, the
// scheduled script fires autonomously on the target host and restores
// pre-capture state.
//
// # Scheduler support
//
// The armer probes the host for at(1) or systemd-run. If neither is
// available the engine returns [api.ErrSchedulerUnavailable] and refuses
// to execute the rule (deadman-timer spec C-01).
//
// # Script generation
//
// The rollback script is generated by dry-running each capturable step's
// [api.RollbackHandler] against a [recordingTransport] that records the
// shell commands without executing them. The commands are written into a
// self-contained POSIX sh script (deadman-timer spec C-02) that removes
// itself on exit (C-05).
//
// # Cancellation
//
// [Armer.Cancel] removes the scheduled job, removes the script file, then
// verifies the job is gone (deadman-timer spec C-04, AC-05).
package deadman

import (
	"context"
	"fmt"
	"io/fs"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"

	"github.com/Hanalyx/kensa/api"
	"github.com/Hanalyx/kensa/internal/engine"
	"github.com/Hanalyx/kensa/internal/handler"
)

// defaultWindow is the minimum timer window per deadman-timer spec C-03.
const defaultWindow = 120 * time.Second

// scriptDir is where the rollback script is staged.
//
// NOT /tmp, where this used to live. Debian-family hosts clear /tmp at boot,
// and not because it is tmpfs -- that was the hypothesis, and it was wrong.
// Ubuntu ships `D /tmp 1777 root root 30d`, and
// `systemd-tmpfiles --create --remove --boot` runs before sysinit.target, well
// before atd. Reproduced in containers: that command deletes
// /tmp/kensa-rollback-<uuid>.sh on ubuntu:24.04 and leaves it on
// rockylinux:9. An at(1) job would then survive the reboot and find its script
// gone, which is the one case the at(1) leg exists to cover.
//
// /var/lib/kensa is what internal/bootguard already uses for state that has to
// outlive a boot. The rollback commands need root regardless, so a root-owned
// directory costs nothing the deadman did not already require.
const scriptDir = "/var/lib/kensa/deadman"

// lockDir is where the rollback script's mutual-exclusion lock lives, and it is
// deliberately NOT scriptDir.
//
// The lock exists to stop the two armed legs running the rollback at the same
// moment. That is a within-one-boot concern: across a reboot the systemd-run
// leg no longer exists at all, so only the at(1) job remains and it SHOULD run
// -- that is the entire reason the at leg is armed. A lock in a boot-persistent
// directory inverts this. A rollback killed mid-flight (kill -9, or the power
// cut that prompted the operator to reboot) leaves the lock behind, and the
// at leg then finds it, exits 0, and reverts nothing. Reproduced on RHEL 9.6:
// after killing the first leg the lock survived, and the second leg ran zero
// rollback commands.
//
// /run is tmpfs on every systemd host (verified on RHEL 8.10, 9.6 and 10.1) and
// is empty after a reboot, so a boot-scoped lock cannot outlive the condition
// it guards.
const lockDir = "/run/kensa/deadman"

// schedulerKind identifies which scheduler was detected on the host.
type schedulerKind string

const (
	schedulerAt         schedulerKind = "at"
	schedulerSystemdRun schedulerKind = "systemd-run"
)

// armedJob holds the state for one armed deadman timer.
type armedJob struct {
	// agentMode distinguishes agent-RPC arms (true) from
	// shell-based at(1)/systemd-run arms (false). Set by
	// armViaAgent / armViaShell respectively. Replaces the
	// empty-scriptPath sentinel pattern (P2-1 fix).
	agentMode bool
	// inert marks an arm for a transaction with nothing to roll back, so
	// nothing was scheduled. Cancel must still resolve it: the engine holds
	// armed=true and reads a Cancel error as "the deadman will fire".
	inert bool
	// scheduled holds every scheduler that accepted the job. Both are armed
	// where both are usable: see armViaShell for why, Cancel for the
	// obligation that creates.
	scheduled  []scheduledJob
	scriptPath string
	firesAt    int64
}

// scheduledJob is one accepted timer. jobID is at(1)'s numeric job ID or
// systemd-run's unit name.
type scheduledJob struct {
	scheduler schedulerKind
	jobID     string
}

// Armer is the production DeadmanArmer. Construct with [New].
//
// Armer satisfies the engine's [engine.DeadmanArmer] interface. Callers
// should use [engine.WithDeadman] to inject it into an [engine.Engine]:
//
//	eng := engine.New(engine.WithDeadman(deadman.New(0, nil)))
//
// **D-005 dispatch.** When the engine has an AgentClient set
// via WithAgentClient AND Armer satisfies the engine's
// AgentAwareDeadmanArmer interface, engine.New calls
// UseAgentClient(c) to wire the agent-mode dispatch path.
// Arm/Cancel then route ArmDeadman/CancelDeadman RPCs
// instead of the at(1)/systemd-run shell-based scheduler.
// Direct-SSH callers (no AgentClient wired) get the
// shell-based path unchanged (Q1.c ratification).
type Armer struct {
	window   time.Duration
	registry *handler.Registry

	mu   sync.Mutex
	jobs map[uuid.UUID]*armedJob

	// agentClient is the optional agent-mode dispatch
	// channel; set via UseAgentClient. When nil, Arm/Cancel
	// use the shell-based at(1)/systemd-run path.
	agentClient engine.DeadmanAgentClient
}

// UseAgentClient wires the agent-mode dispatch channel.
// Satisfies the engine's AgentAwareDeadmanArmer capability
// interface (parameter type must match
// engine.DeadmanAgentClient exactly so Go's named-type
// interface satisfaction holds at the engine.New type
// assertion site). Called by engine.New when
// WithAgentClient is set.
func (a *Armer) UseAgentClient(c engine.DeadmanAgentClient) {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.agentClient = c
}

// New returns an Armer with the given timer window. Pass 0 to use the
// default 120-second window (deadman-timer spec C-03). Pass nil for
// registry to use [handler.Default].
func New(window time.Duration, registry *handler.Registry) *Armer {
	if window <= 0 {
		window = defaultWindow
	}
	if registry == nil {
		registry = handler.Default()
	}
	return &Armer{
		window:   window,
		registry: registry,
		jobs:     make(map[uuid.UUID]*armedJob),
	}
}

// Arm implements engine.DeadmanArmer.
//
// It probes for a scheduler, dry-runs each capturable step's rollback
// handler to collect shell commands, generates a POSIX shell script,
// uploads it to <scriptDir>/kensa-rollback-<txn-id>.sh, schedules it, and
// verifies the job appears in the scheduler's queue.
//
// Failure modes:
//   - Neither at(1) nor systemd-run available → [api.ErrSchedulerUnavailable].
//   - Rollback dry-run fails (unknown mechanism) → typed error.
//   - Script upload fails (disk full, permissions) → typed error; no
//     apply will run because the engine fails on Arm error.
//   - Post-schedule verification fails → typed error; script file is
//     removed before returning.
func (a *Armer) Arm(ctx context.Context, transport api.Transport, txnID uuid.UUID, preStates []api.PreState) (string, int64, error) {
	a.mu.Lock()
	agentClient := a.agentClient
	a.mu.Unlock()

	// D-005 dispatch: agent-mode uses in-process timerfd/
	// pidfd/signalfd via RPC; direct-SSH falls back to the
	// at(1)/systemd-run shell path.
	if agentClient != nil {
		return a.armViaAgent(ctx, agentClient, txnID, preStates)
	}
	return a.armViaShell(ctx, transport, txnID, preStates)
}

// armViaAgent dispatches the deadman through the agent's
// ArmDeadman RPC. The agent spawns an in-process event-loop
// goroutine; on wakeup it executes the rollback commands
// generated by our dry-run.
//
// Per Q1 ratification: if the agent RPC fails, the arm
// fails. We do NOT fall back to the shell path silently —
// the operator can opt into shell via KENSA_NO_AGENT=1.
func (a *Armer) armViaAgent(ctx context.Context, agentClient engine.DeadmanAgentClient, txnID uuid.UUID, preStates []api.PreState) (string, int64, error) {
	// Generate rollback commands via dry-run, same as shell
	// path (the agent executes the commands verbatim).
	cmds, err := a.collectRollbackCommands(preStates)
	if err != nil {
		return "", 0, fmt.Errorf("deadman: build rollback commands: %w", err)
	}
	armable, err := checkRollbackCommands(cmds, preStates)
	if err != nil {
		return "", 0, err
	}
	if !armable {
		return "", a.recordInert(txnID), nil
	}
	windowSec := int64(a.window.Seconds())
	firesAt, err := agentClient.ArmDeadman(ctx, txnID.String(), windowSec, cmds)
	if err != nil {
		return "", 0, fmt.Errorf("deadman: ArmDeadman RPC: %w", err)
	}
	a.mu.Lock()
	a.jobs[txnID] = &armedJob{
		agentMode: true,
		firesAt:   firesAt,
	}
	a.mu.Unlock()
	// scriptPath is empty for agent-mode (no script on disk).
	return "", firesAt, nil
}

// armViaShell is the pre-D-005 path: at(1)/systemd-run
// scheduling. Preserved per Q1.c for direct-SSH operators
// where agent bootstrap isn't viable.
func (a *Armer) armViaShell(ctx context.Context, transport api.Transport, txnID uuid.UUID, preStates []api.PreState) (string, int64, error) {
	// @spec deadman-timer
	// @ac AC-01 — detect scheduler availability.
	scheds := availableSchedulers(ctx, transport)
	if len(scheds) == 0 {
		return "", 0, api.ErrSchedulerUnavailable
	}

	// @ac AC-02 — generate rollback commands via dry-run.
	cmds, err := a.collectRollbackCommands(preStates)
	if err != nil {
		return "", 0, fmt.Errorf("deadman: build rollback commands: %w", err)
	}
	armable, err := checkRollbackCommands(cmds, preStates)
	if err != nil {
		return "", 0, err
	}
	if !armable {
		return "", a.recordInert(txnID), nil
	}

	scriptPath := fmt.Sprintf("%s/kensa-rollback-%s.sh", scriptDir, txnID)
	scriptContent := buildScript(txnID, cmds)

	// @ac AC-03 — upload script mode 0700.
	if err := uploadScript(ctx, transport, scriptContent, scriptPath); err != nil {
		return "", 0, fmt.Errorf("deadman: upload rollback script: %w", err)
	}

	// @ac AC-04 — schedule and verify.
	//
	// EVERY usable scheduler is armed, not the first that accepts, because the
	// two cover different failures and neither covers both.
	//
	// systemd-run is the timer that fires. Its executor is PID 1, so there is
	// no state where the job is accepted and nothing runs it -- which at(1)
	// has whenever atd is down.
	//
	// at(1) is the backstop across a REBOOT. A systemd-run transient unit
	// lives in /run/systemd/transient, which is tmpfs, so a power cycle erases
	// it. at(1)'s job is a file in /var/spool/at and atd runs overdue jobs when
	// it starts. The exposed case is the deadman's own reason for existing: a
	// change costs Kensa the control channel before commit, the operator
	// power-cycles the host, and the reboot does not undo an on-disk change.
	//
	// Both legs run the same script, which takes an atomic lock before doing
	// anything, so whichever fires first makes the other a no-op. Self-deletion
	// was NOT enough: it removes the file when the first copy finishes, and two
	// copies launched 50ms apart both ran to completion.
	//
	// A scheduler that is installed can still refuse -- systemd-run without
	// privilege, at(1) with its daemon stopped -- so a refusal advances rather
	// than failing the arm. Each leaves nothing behind when it refuses.
	var (
		scheduled []scheduledJob
		earliest  time.Duration
		attempts  []string
	)
	for _, candidate := range scheds {
		id, fires, serr := schedule(ctx, transport, candidate, txnID, scriptPath, a.window)
		if serr != nil {
			attempts = append(attempts, fmt.Sprintf("%s: %v", candidate, serr))
			continue
		}
		scheduled = append(scheduled, scheduledJob{scheduler: candidate, jobID: id})
		if earliest == 0 || fires < earliest {
			earliest = fires
		}
	}
	if len(scheduled) == 0 {
		// Clean up the orphaned script file before returning.
		_, _ = transport.Run(ctx, "rm -f "+shellQuote(scriptPath))
		// Wrap the sentinel: "installed but every one refused" is the same
		// outcome for a caller as "none installed", and
		// api.ErrSchedulerUnavailable is the frozen public name for it.
		return "", 0, fmt.Errorf("deadman: no scheduler could arm the timer (%s): %w",
			strings.Join(attempts, "; "), api.ErrSchedulerUnavailable)
	}
	firesAt := time.Now().Add(earliest).Unix()

	a.mu.Lock()
	a.jobs[txnID] = &armedJob{
		agentMode:  false,
		scheduled:  scheduled,
		scriptPath: scriptPath,
		firesAt:    firesAt,
	}
	a.mu.Unlock()

	return scriptPath, firesAt, nil
}

// recordInert registers an arm that scheduled nothing, so Cancel resolves
// cleanly. The engine sets armed=true on any successful Arm and reads a Cancel
// error as "the deadman will fire", which would trigger a needless rollback.
func (a *Armer) recordInert(txnID uuid.UUID) int64 {
	firesAt := time.Now().Add(a.window).Unix()
	a.mu.Lock()
	a.jobs[txnID] = &armedJob{inert: true, firesAt: firesAt}
	a.mu.Unlock()
	return firesAt
}

// Cancel implements engine.DeadmanArmer.
//
// It removes the scheduled job, removes the script file, and verifies
// the job is no longer present in the scheduler's queue (deadman-timer
// spec C-04, AC-05, C-05, AC-08).
//
// Returns [api.ErrNoActiveDeadman] when no timer is armed for txnID.
//
// Failure modes:
//   - atrm/systemctl fails → typed error; the deadman may still fire.
//   - Post-cancel verification shows job still present → typed error.
//   - Script rm fails → logged anomaly but does not fail the cancel;
//     residual files are hygiene failures per spec C-05.
func (a *Armer) Cancel(ctx context.Context, transport api.Transport, txnID uuid.UUID) error {
	a.mu.Lock()
	job, ok := a.jobs[txnID]
	if !ok {
		a.mu.Unlock()
		return api.ErrNoActiveDeadman
	}
	// P1-4 fix: do NOT delete from a.jobs until the cancel
	// operation succeeds. On RPC/shell failure, the entry
	// stays in the map so the engine can retry (or the
	// operator can inspect via a future status RPC).
	agentClient := a.agentClient
	a.mu.Unlock()

	if job.inert {
		a.mu.Lock()
		delete(a.jobs, txnID)
		a.mu.Unlock()
		return nil
	}

	// D-005 dispatch: agent-mode jobs are tagged
	// `agentMode=true` (set by armViaAgent); shell-mode jobs
	// carry the full at-job/systemctl-unit context AND
	// agentMode=false. The explicit flag replaces the
	// empty-scriptPath sentinel (P2-1).
	if agentClient != nil && job.agentMode {
		if err := a.cancelViaAgent(ctx, agentClient, txnID); err != nil {
			return err
		}
		a.mu.Lock()
		delete(a.jobs, txnID)
		a.mu.Unlock()
		return nil
	}

	// Ask whether the deadman already fired BEFORE canceling anything. Both
	// the stop below and the rm further down destroy evidence, and the answer
	// changes the transaction's verdict: a fired timer means this host has
	// already been reverted, so recording StatusCommitted would leave the log
	// and the machine disagreeing with nothing to reconcile them.
	if deadmanAlreadyFired(ctx, transport, txnID) {
		_, _ = transport.Run(ctx, fmt.Sprintf("rm -f %s %s",
			shellQuote(firedMarkerPath(txnID)), shellQuote(job.scriptPath)))
		_ = cancelJob(ctx, transport, job) // tear down the other leg regardless
		a.mu.Lock()
		delete(a.jobs, txnID)
		a.mu.Unlock()
		return fmt.Errorf("deadman: the rollback timer for %s had already FIRED before "+
			"cancel; the change did not survive and must not be recorded as committed", txnID)
	}

	// @ac AC-05 — cancel scheduled job and verify.
	if err := cancelJob(ctx, transport, job); err != nil {
		return err
	}

	// @ac AC-08 — remove script file.
	_, _ = transport.Run(ctx, "rm -f "+shellQuote(job.scriptPath))

	a.mu.Lock()
	delete(a.jobs, txnID)
	a.mu.Unlock()
	return nil
}

// cancelViaAgent sends a CancelDeadman RPC. If the agent
// reports no matching arm (wasActive=false), we treat it as
// success — the engine called Cancel after the timer fired
// or after a tear-down race; the desired end-state (no
// rollback pending for txnID) is already achieved.
func (a *Armer) cancelViaAgent(ctx context.Context, agentClient engine.DeadmanAgentClient, txnID uuid.UUID) error {
	_, err := agentClient.CancelDeadman(ctx, txnID.String())
	if err != nil {
		return fmt.Errorf("deadman: CancelDeadman RPC: %w", err)
	}
	return nil
}

// availableSchedulers returns the schedulers present on the host, in the order
// they should be tried.
//
// systemd-run leads because it is the timer that actually fires. at(1) is two
// programs: `at` writes a job into a spool and atd(8) executes it. Either can
// exist without the other, so at can accept a job, exit zero and print a job
// number on a host where nothing will ever run it. systemd-run has no
// equivalent state, because the process that would run its transient timer is
// PID 1.
//
// Returning a LIST rather than a choice matters as much as the order. Presence
// is not usability: systemd-run refuses without privilege where at(1) on the
// same host schedules fine, and at(1) refuses when its daemon is dead where
// systemd-run works. The caller arms every one that accepts.
func availableSchedulers(ctx context.Context, transport api.Transport) []schedulerKind {
	var out []schedulerKind
	probe := func(cmd, marker string, kind schedulerKind) {
		res, err := transport.Run(ctx, cmd)
		if err == nil && strings.Contains(res.Stdout, marker) {
			out = append(out, kind)
		}
	}
	probe("command -v systemd-run 2>/dev/null && echo __SDR_FOUND__ || true", "__SDR_FOUND__", schedulerSystemdRun)
	probe("command -v at 2>/dev/null && echo __AT_FOUND__ || true", "__AT_FOUND__", schedulerAt)
	return out
}

// checkRollbackCommands reports whether there is anything for a timer to run.
//
// An empty command list means nothing to roll back, and the arm is skipped:
// nothing is scheduled, no script is uploaded, and Cancel still resolves. That
// is the honest state, and it is reachable for good reasons -- roughly ten
// shipped handlers return Success with no command by design when the system
// already matched the captured state (package_absent "was absent at capture",
// service_enabled on a unit that was already enabled and running, file_absent,
// config_append, and others).
//
// An earlier version of this treated "capturable steps yielded no commands" as
// proof of a broken capture and failed the arm. That premise does not hold: an
// empty rollback follows whenever Apply itself is a no-op, which is exactly
// when those handlers report success with nothing to do. It would have
// misdiagnosed a correct capture as broken, and the message would have sent
// the reader hunting a defect that was not there.
//
// The case that premise was aimed at -- a capture whose values are wrong, so
// the rollback builders silently match nothing -- is caught where it can
// actually be proven, at capture time in the handler:
// servicedbus.CheckPreStateOrientation refuses a pre-state whose two fields
// hold each other's values, and the transaction aborts before Apply. A command
// count cannot tell that case from a legitimate no-op, and guessing from here
// was the wrong layer.
func checkRollbackCommands(cmds []string, _ []api.PreState) (armable bool, err error) {
	return len(cmds) > 0, nil
}

// collectRollbackCommands dry-runs each capturable step's rollback handler
// using a [recordingTransport] and returns the shell commands in rollback
// execution order (reverse of apply order, per deadman-timer spec AC-02).
func (a *Armer) collectRollbackCommands(preStates []api.PreState) ([]string, error) {
	rec := &recordingTransport{}
	ctx := context.Background()

	for i := len(preStates) - 1; i >= 0; i-- {
		ps := preStates[i]
		if !ps.Capturable {
			continue
		}
		h, ok := a.registry.Get(ps.Mechanism)
		if !ok {
			return nil, fmt.Errorf("unknown mechanism %q", ps.Mechanism)
		}
		rh, ok := h.(api.RollbackHandler)
		if !ok {
			return nil, fmt.Errorf("mechanism %q does not implement RollbackHandler", ps.Mechanism)
		}
		pre := ps
		if _, err := rh.Rollback(ctx, rec, &pre); err != nil {
			return nil, fmt.Errorf("dry-run rollback step %d (%s): %w", ps.StepIndex, ps.Mechanism, err)
		}
	}
	return rec.cmds, nil
}

// buildScript generates a self-contained POSIX sh rollback script.
// The script runs cmds in order (already in reverse-apply order)
// and removes itself on exit (deadman-timer spec C-05).
func buildScript(txnID uuid.UUID, cmds []string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Kensa deadman rollback script\n")
	fmt.Fprintf(&b, "# Transaction:  %s\n", txnID)
	fmt.Fprintf(&b, "# Generated at: %s\n", time.Now().UTC().Format(time.RFC3339))
	b.WriteString("# This script fires if Kensa loses its control-channel connection\n")
	b.WriteString("# after apply. It restores the pre-apply state captured before any\n")
	b.WriteString("# changes ran. Self-deletes on exit per deadman-timer spec C-05.\n")
	b.WriteString("set -eu\n")
	b.WriteString("\n")
	// Two schedulers are armed for the same transaction, so two copies of this
	// script can start. Self-deletion does NOT prevent that: `trap cleanup
	// EXIT` removes the file when the first copy FINISHES, and two copies
	// launched 50ms apart both ran to completion in testing, fully overlapped.
	// Any rollback lasting longer than the gap between the legs would run twice
	// against the same host, concurrently.
	//
	// mkdir is the POSIX atomic test-and-set: it fails if the directory exists,
	// in a single operation, with no window between checking and creating.
	// A losing copy exits 0 -- "the rollback is already running" is success
	// from where it stands, and a non-zero exit would only produce noise in the
	// scheduler's mail.
	fmt.Fprintf(&b, "LOCK=%s/kensa-rollback-%s.lock\n", lockDir, txnID)
	fmt.Fprintf(&b, "FIRED=%s\n", firedMarkerPath(txnID))
	fmt.Fprintf(&b, "mkdir -p %s 2>/dev/null || true\n", lockDir)
	b.WriteString("if ! mkdir \"$LOCK\" 2>/dev/null; then\n")
	// A held lock is only a reason to stand down if its holder is still alive.
	// kill -9 skips the EXIT trap, so a rollback killed mid-flight leaves the
	// lock behind; the backstop leg would then find it and revert nothing --
	// exactly when reverting matters most. `kill -0` tests for the process
	// without signalling it.
	b.WriteString("    if [ -r \"$LOCK/pid\" ] && kill -0 \"$(cat \"$LOCK/pid\")\" 2>/dev/null; then\n")
	b.WriteString("        exit 0   # the other scheduler's copy is running it now\n")
	b.WriteString("    fi\n")
	b.WriteString("    rm -rf \"$LOCK\"\n")
	b.WriteString("    mkdir \"$LOCK\" 2>/dev/null || exit 0\n")
	b.WriteString("fi\n")
	b.WriteString("echo $$ > \"$LOCK/pid\" 2>/dev/null || true\n")
	// The marker is written BEFORE any rollback command and is NOT removed on
	// exit. Cancel reads it to tell "the timer was canceled" from "the timer
	// fired and this host has been reverted" -- opposite outcomes that the
	// scheduler's own state cannot distinguish.
	//
	// systemd was the obvious place to ask and it cannot answer. A transient
	// timer carries RemainAfterElapse=no, so within about a second of elapsing
	// the unit is garbage-collected: `systemctl show -p ActiveState -p
	// LastTriggerUSecMonotonic` then returns inactive/0/not-found, BYTE
	// IDENTICAL to a timer that was canceled before it ever ran. Measured on
	// RHEL 9.6, both cases side by side. Reading those properties was inert.
	//
	// Written before the commands rather than after, because a rollback that
	// started and then failed has still begun reverting the host; reporting
	// that as a clean cancel would be the more dangerous error.
	b.WriteString("echo \"$(date -u '+%Y-%m-%dT%H:%M:%SZ')\" > \"$FIRED\" 2>/dev/null || true\n")
	b.WriteString("cleanup() { rm -rf \"$LOCK\"; rm -f \"$0\"; }\n")
	b.WriteString("trap cleanup EXIT\n")
	b.WriteString("\n")
	for i, cmd := range cmds {
		fmt.Fprintf(&b, "# rollback step %d\n", i+1)
		b.WriteString(cmd)
		b.WriteString("\n")
	}
	return b.String()
}

// firedMarkerPath is where the rollback script records that it ran. It
// deliberately outlives both the script and the lock, which the script removes
// on exit, and it is scheduler-agnostic: at(1) and systemd-run leave no
// comparable trace, and systemd's own is garbage-collected within a second.
func firedMarkerPath(txnID uuid.UUID) string {
	return fmt.Sprintf("%s/kensa-rollback-%s.fired", scriptDir, txnID)
}

// deadmanAlreadyFired reports whether the rollback script ran for this
// transaction, reading the marker the script writes before touching anything.
func deadmanAlreadyFired(ctx context.Context, transport api.Transport, txnID uuid.UUID) bool {
	marker := firedMarkerPath(txnID)
	res, err := transport.Run(ctx, fmt.Sprintf("test -e %s && echo __FIRED__ || true", shellQuote(marker)))
	return err == nil && strings.Contains(res.Stdout, "__FIRED__")
}

// uploadScript writes content to remotePath on the host with mode 0700.
// Uses printf to write the content via the control-channel Run path
// (avoids scp and local temp files).
func uploadScript(ctx context.Context, transport api.Transport, content, remotePath string) error {
	// Use printf with single-quoted content (shellQuote handles embedded
	// single quotes via the standard '\''-escape idiom).
	cmd := fmt.Sprintf("mkdir -p %s && chmod 0700 %s && printf '%%s' %s > %s && chmod 0700 %s",
		shellQuote(scriptDir), shellQuote(scriptDir),
		shellQuote(content), shellQuote(remotePath), shellQuote(remotePath),
	)
	res, err := transport.Run(ctx, cmd)
	if err != nil {
		return err
	}
	if !res.OK() {
		return fmt.Errorf("upload failed (exit %d): %s", res.ExitCode, res.Stderr)
	}
	return nil
}

// schedule submits the rollback script for deferred execution. Returns the
// job ID (at numeric ID or systemd-run unit name) for cancellation.
// It returns the job ID for cancellation and the SOONEST the job can fire.
// Those differ per scheduler: systemd-run is given an absolute deadline and
// delivers the window itself, while at(1) rounds up to a whole minute and
// truncates its base, so its floor is (N-1) minutes. The caller reports the
// earliest across armed schedulers, because that is when a rollback can land.
func schedule(ctx context.Context, transport api.Transport, sched schedulerKind, txnID uuid.UUID, scriptPath string, window time.Duration) (string, time.Duration, error) {
	windowSec := int(window.Seconds())
	switch sched {
	case schedulerAt:
		id, err := scheduleAt(ctx, transport, scriptPath, windowSec)
		return id, time.Duration(atWindowMinutes(windowSec)-1) * time.Minute, err
	case schedulerSystemdRun:
		id, err := scheduleSystemdRun(ctx, transport, txnID, scriptPath, windowSec)
		return id, window, err
	}
	return "", 0, fmt.Errorf("deadman: unknown scheduler %q", sched)
}

// atWindowMinutes converts a window in seconds to the whole minutes at(1)
// accepts, choosing the smallest count that cannot fire EARLY.
//
// Two facts drive this, and the second is easy to miss.
//
// at(1) has no sub-minute unit. `at now + 120 seconds` is a parse error
// ("syntax error. Last token seen: s", "Garbled time", exit 1) on every
// implementation, not a distro quirk. Kensa emitted exactly that from its
// first release.
//
// at(1) also TRUNCATES its base time to the whole minute before adding the
// offset, so `now + N minutes` fires at the start of the Nth minute from now,
// not N minutes from now. Measured on RHEL 9 (at-3.1.23): a 2-minute spec
// submitted at :03, :10 and :17 past the minute scheduled 117s, 110s and 103s
// out. The delivered window is ((N-1)*60, N*60], always SHORTER than N
// minutes and never longer.
//
// A naive ceil(window/60) is therefore wrong in a way that reads as right: it
// looks like rounding up and behaves like rounding down. A 120-second window
// would become a 2-minute spec delivering 61 to 120 seconds, so the deadman
// could fire mid-apply and revert a transaction still legitimately in flight.
//
// Guaranteeing delivered >= window needs (N-1)*60 >= window, so
// N = ceil((window+60)/60). The cost is up to one extra minute of exposure
// for an uncommitted change: bounded, recoverable, and the right direction to
// err.
func atWindowMinutes(windowSec int) int {
	if windowSec < 0 {
		windowSec = 0
	}
	return (windowSec + 119) / 60
}

// scheduleAt submits the script to at(1) and verifies the job appears in atq.
func scheduleAt(ctx context.Context, transport api.Transport, scriptPath string, windowSec int) (string, error) {
	// at(1) reads the command from stdin. We use a shell one-liner to
	// avoid multi-line stdin over the transport.
	cmd := fmt.Sprintf("echo sh %s | at now + %d minutes 2>&1",
		shellQuote(scriptPath), atWindowMinutes(windowSec))
	res, err := transport.Run(ctx, cmd)
	if err != nil {
		return "", err
	}
	// at(1) exit code is 0 on success but may emit the job summary to stderr.
	combined := res.Stdout + "\n" + res.Stderr
	jobID := extractAtJobID(combined)
	if jobID == "" {
		return "", fmt.Errorf("deadman: could not parse at job ID from output: %q", combined)
	}

	// @ac AC-13 — a queued job is not a scheduled job.
	//
	// at(1) writes to a spool; atd(8) runs what is in it. They are separate,
	// and either can be present without the other. With atd stopped, at exits
	// ZERO, prints a normal "job N at <time>" line, and queues the job. Only
	// one line distinguishes the two cases, and it lands in the same combined
	// stream the job ID was parsed from:
	//
	//   job 4 at Sun Aug  2 12:55:00 2026
	//   Can't open /var/run/atd.pid to signal atd. No atd running?
	//
	// atq then lists the job, because atq reads the spool too. So every signal
	// the caller checks says "armed" while nothing will ever fire. Verified on
	// RHEL 9.7. This matters on ordinary hosts: the RHEL `at` package's %post
	// enables atd without starting it, so a freshly installed host sits in
	// exactly this state until it reboots.
	//
	// Reading at(1)'s own diagnostic is deliberate, rather than probing
	// `systemctl is-active atd`. The at path exists to serve hosts where
	// systemd-run is unavailable, which includes hosts with no systemd at all,
	// and a systemctl probe answers nothing useful there. It also does not
	// depend on the unit being named atd rather than at.
	if !res.OK() || atdNotRunning(combined) {
		// at accepted the job, so it is sitting in the spool. Remove it: if
		// atd is started later, an orphaned job would fire a rollback for a
		// transaction that was never armed.
		_, _ = transport.Run(ctx, "atrm "+shellQuote(jobID))
		return "", fmt.Errorf("deadman: at(1) queued job %s but it will not run (exit %d): %s",
			jobID, res.ExitCode, strings.TrimSpace(combined))
	}

	// @ac AC-04 — post-schedule verification.
	if err := verifyAtJobPresent(ctx, transport, jobID); err != nil {
		// Same reasoning: do not leave a job behind that nothing will cancel.
		_, _ = transport.Run(ctx, "atrm "+shellQuote(jobID))
		return "", err
	}
	return jobID, nil
}

// atdDiagnostics are the strings at(1) emits when it has queued a job but
// could not signal the daemon that runs it. Taken verbatim from at-3.1.23;
// both are matched because the wording varies by version and the pid path
// differs across distributions.
var atdDiagnostics = []string{"no atd running", "atd.pid"}

// atdNotRunning reports whether at(1)'s output says the job was queued but
// the daemon was not reachable.
//
// Limitation worth stating: this detects the case at(1) warns about. An
// implementation that queued silently without warning would still pass, so
// this narrows the window rather than closing it. The systemd-run path has no
// equivalent gap, because the process that would run the timer is PID 1.
func atdNotRunning(output string) bool {
	lower := strings.ToLower(output)
	for _, d := range atdDiagnostics {
		if strings.Contains(lower, d) {
			return true
		}
	}
	return false
}

// scheduleSystemdRun submits the script via systemd-run and verifies
// the transient timer unit appears in systemctl list-timers.
func scheduleSystemdRun(ctx context.Context, transport api.Transport, txnID uuid.UUID, scriptPath string, windowSec int) (string, error) {
	unitName := fmt.Sprintf("kensa-rollback-%s", txnID)

	// --on-calendar with an ABSOLUTE timestamp, not --on-active with a
	// relative window. That is the difference between a deadline and a
	// countdown, and the countdown does not hold.
	//
	// A relative --on-active window is RESET TO A FULL FRESH WINDOW by any
	// `systemctl daemon-reload`. Measured on RHEL 9.6: armed for 120s, and
	// after a reload 8.5s later the remaining window was 119.95s rather than
	// 111.5s. `systemctl enable`, `disable` and `mask` each perform an
	// implicit reload, and those are the mechanisms that arm the deadman -- so
	// the timer was pushed back by the very apply it exists to guard, with no
	// bound on how often. End to end on Ubuntu 22.04 a 120-second window fired
	// at 225s, and on RHEL 9.6 the timer never fired at all. An absolute
	// deadline held fixed across three reloads.
	//
	// The timestamp is computed ON THE TARGET, because the calendar spec is
	// interpreted against the target's clock and timezone; computing it here
	// would silently shift the deadline by any controller/target skew. at(1)
	// has always worked this way.
	//
	// AccuracySec is pinned because systemd's DEFAULT IS ONE MINUTE, not one
	// second: a stock transient timer carries AccuracyUSec=1min so systemd can
	// coalesce wakeups. Measured: five 20-second timers armed three seconds
	// apart all fired at one instant, 58-70s late. Present since systemd v236;
	// verified on the oldest fleet target (systemd 239, RHEL 8.10).
	cmd := fmt.Sprintf(
		"systemd-run --unit=%s --on-calendar=\"$(date -d '+%d seconds' '+%%Y-%%m-%%d %%H:%%M:%%S')\" "+
			"--timer-property=AccuracySec=1s -- sh %s",
		shellQuote(unitName), windowSec, shellQuote(scriptPath))
	res, err := transport.Run(ctx, cmd)

	// systemd-run exits 0 once the unit is queued, so any failure AFTER the
	// command reached the host can leave a live transient timer behind. The
	// caller then arms the next scheduler and records only what succeeded, so
	// nothing would ever cancel this one: an untracked timer firing a full
	// rollback against a transaction that has since committed, with no event
	// and no store record. Every exit path below the Run stops the unit first.
	stopOrphan := func() {
		_, _ = transport.Run(ctx, fmt.Sprintf(
			"systemctl stop %s.timer 2>/dev/null; systemctl reset-failed %s 2>/dev/null; true",
			shellQuote(unitName), shellQuote(unitName)))
	}

	if err != nil {
		// A transport error does not prove the command did not run: it may
		// have executed and the reply been lost. Stop the unit blind.
		stopOrphan()
		return "", err
	}
	if !res.OK() {
		stopOrphan()
		return "", fmt.Errorf("deadman: systemd-run failed (exit %d): %s", res.ExitCode, res.Stderr)
	}
	// @ac AC-04 — post-schedule verification.
	if err := verifySystemdUnitPresent(ctx, transport, unitName); err != nil {
		stopOrphan()
		return "", err
	}
	return unitName, nil
}

// cancelJob removes EVERY scheduled job for the transaction and verifies each
// is gone (deadman-timer spec AC-05, C-10).
//
// Arming two schedulers makes a partial cancel possible, and a partial cancel
// is the most dangerous state this package can produce: Cancel runs on the
// COMMIT path, so a survivor fires a full rollback against a transaction that
// already succeeded, unprompted and with no operator watching. Every job is
// attempted even after one fails -- returning early would guarantee the
// untracked survivor -- and ANY failure fails the cancel. The engine reads that
// as "the deadman will fire", rolls back in band and reports it, which beats a
// committed status a timer is about to contradict.
func cancelJob(ctx context.Context, transport api.Transport, job *armedJob) error {
	var failures []string
	for _, sj := range job.scheduled {
		if err := cancelOne(ctx, transport, sj); err != nil {
			failures = append(failures, err.Error())
		}
	}
	if len(failures) > 0 {
		return fmt.Errorf("deadman: cancel failed for %d of %d armed timers: %s",
			len(failures), len(job.scheduled), strings.Join(failures, "; "))
	}
	return nil
}

// cancelOne removes a single scheduled job and verifies it is gone.
func cancelOne(ctx context.Context, transport api.Transport, sj scheduledJob) error {
	switch sj.scheduler {
	case schedulerAt:
		res, err := transport.Run(ctx, "atrm "+shellQuote(sj.jobID))
		if err != nil {
			return fmt.Errorf("atrm: %w", err)
		}
		if !res.OK() {
			return fmt.Errorf("atrm failed (exit %d): %s", res.ExitCode, res.Stderr)
		}
		return verifyAtJobGone(ctx, transport, sj.jobID)

	case schedulerSystemdRun:
		// Stop the TIMER only, never the bare unit name.
		//
		// `systemctl stop kensa-rollback-<uuid>` resolves to the .service, and
		// if the timer has already elapsed that service is the rollback
		// itself. Stopping it mid-flight leaves the host partially reverted --
		// worse than either completing or never starting. Canceling a timer
		// that has not fired is what this is for; a timer that HAS fired is
		// not cancellable and is reported as such by verifySystemdUnitGone.
		stopCmd := fmt.Sprintf("systemctl stop %s.timer 2>/dev/null; true", shellQuote(sj.jobID))
		if _, err := transport.Run(ctx, stopCmd); err != nil {
			return fmt.Errorf("systemctl stop: %w", err)
		}
		return verifySystemdUnitGone(ctx, transport, sj.jobID)
	}
	return fmt.Errorf("unknown scheduler %q", sj.scheduler)
}

// atqListsJob reports whether atq output lists exactly this job.
//
// The match is anchored at BOTH ends of the ID: line start and the tab that
// follows it. Real atq output is "73\tSun Aug  2 18:25:00 2026 a root", so a
// bare substring test for "3" matches job 73, and a tab-suffixed test for "3\t"
// still does -- the tab fixes the prefix collision (4 against 42) and leaves
// the suffix one (3 against 73) wide open. Both ends are needed.
//
// This is the last gate before the engine applies, and its sibling on the
// cancel path fails in the more dangerous direction: a false "still present"
// makes Cancel fail, and the engine answers that by rolling back a healthy
// transaction.
func atqListsJob(stdout, jobID string) bool {
	for _, line := range strings.Split(stdout, "\n") {
		id, _, ok := strings.Cut(strings.TrimLeft(line, " \t"), "\t")
		if ok && id == jobID {
			return true
		}
	}
	return false
}

// verifyAtJobPresent confirms jobID appears in atq output.
func verifyAtJobPresent(ctx context.Context, transport api.Transport, jobID string) error {
	res, err := transport.Run(ctx, "atq 2>/dev/null")
	if err != nil {
		return fmt.Errorf("deadman: atq check: %w", err)
	}
	if !atqListsJob(res.Stdout, jobID) {
		return fmt.Errorf("deadman: job %s not found in atq after scheduling", jobID)
	}
	return nil
}

// verifyAtJobGone confirms jobID is absent from atq output.
func verifyAtJobGone(ctx context.Context, transport api.Transport, jobID string) error {
	res, err := transport.Run(ctx, "atq 2>/dev/null")
	if err != nil {
		return fmt.Errorf("deadman: atq check after cancel: %w", err)
	}
	if atqListsJob(res.Stdout, jobID) {
		return fmt.Errorf("deadman: job %s still present in atq after cancel", jobID)
	}
	return nil
}

// verifySystemdUnitPresent confirms the transient timer unit appears active.
func verifySystemdUnitPresent(ctx context.Context, transport api.Transport, unitName string) error {
	res, err := transport.Run(ctx, fmt.Sprintf(
		"systemctl show -p LoadState --value %s.timer 2>/dev/null || true",
		shellQuote(unitName),
	))
	if err != nil {
		return fmt.Errorf("deadman: systemctl show after schedule: %w", err)
	}
	state := strings.TrimSpace(res.Stdout)
	if state == "not-found" || state == "" {
		return fmt.Errorf("deadman: unit %s.timer not found after scheduling", unitName)
	}
	return nil
}

// verifySystemdUnitGone confirms the transient timer unit is no longer active.
func verifySystemdUnitGone(ctx context.Context, transport api.Transport, unitName string) error {
	// Properties are read BY NAME, not by position. `systemctl show -p A -p B
	// --value` prints in systemd's own order, not the order asked for, and
	// reading that output positionally is precisely the bug that leaves the
	// service handlers restoring the wrong fields today.
	res, err := transport.Run(ctx, fmt.Sprintf(
		"systemctl show -p ActiveState -p LastTriggerUSecMonotonic %s.timer 2>/dev/null; true",
		shellQuote(unitName),
	))
	if err != nil {
		// A transport error means the state is UNKNOWN, and unknown is not
		// canceled. This used to return nil -- "could not verify" was
		// recorded as success, which is the one direction a safety gate must
		// never fail in. The engine answers a cancel error with an in-band
		// rollback, so the cost of being wrong here is a redundant restore;
		// the cost of the old behavior was a live timer reported as gone.
		return fmt.Errorf("deadman: could not verify %s.timer was canceled: %w", unitName, err)
	}
	props := parseShowProperties(res.Stdout)

	if props["ActiveState"] == "active" {
		return fmt.Errorf("deadman: unit %s.timer still active after cancel", unitName)
	}

	// Whether the timer FIRED cannot be answered from here. A transient timer
	// carries RemainAfterElapse=no, so within about a second of elapsing the
	// unit is garbage-collected and these same properties read
	// inactive/0/not-found -- byte identical to a timer canceled before it
	// ever ran. Measured on RHEL 9.6 with both cases side by side. That
	// question is answered by the marker the rollback script writes; see
	// deadmanAlreadyFired, which Cancel consults before reaching this point.

	return nil
}

// parseShowProperties reads `systemctl show` KEY=VALUE output into a map.
//
// The non---value form is used deliberately. With --value systemd prints bare
// values in ITS order rather than the requested one, and a positional read of
// that output is the live defect in the service handlers: `systemctl show -p
// UnitFileState -p ActiveState --value` returns ActiveState first, so every
// captured value lands in the wrong field. Naming the keys costs one parse and
// removes the whole class.
func parseShowProperties(out string) map[string]string {
	props := make(map[string]string)
	for _, line := range strings.Split(out, "\n") {
		k, v, ok := strings.Cut(strings.TrimSpace(line), "=")
		if ok {
			props[k] = v
		}
	}
	return props
}

// Job number extraction helper for at(1) scheduling.
// At(1) writes "job N at <date>" to stderr (POSIX) or stdout (some implementations);
// extractAtJobID returns the numeric job ID from that output.
func extractAtJobID(output string) string {
	for _, line := range strings.Split(output, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "job ") {
			fields := strings.Fields(line)
			if len(fields) >= 2 {
				return fields[1]
			}
		}
	}
	return ""
}

// recordingTransport implements [api.Transport] for dry-run rollback.
// [Run] records shell commands without executing them. All other
// methods are no-ops so rollback handlers can call them safely.
type recordingTransport struct {
	cmds []string
}

func (r *recordingTransport) Run(_ context.Context, cmd string) (*api.CommandResult, error) {
	r.cmds = append(r.cmds, cmd)
	return &api.CommandResult{ExitCode: 0}, nil
}

func (r *recordingTransport) Put(_ context.Context, _, _ string, _ fs.FileMode) error { return nil }
func (r *recordingTransport) Get(_ context.Context, _, _ string) error                { return nil }
func (r *recordingTransport) Close() error                                            { return nil }
func (r *recordingTransport) ControlChannelSensitive() bool                           { return false }

// shellQuote wraps s in single quotes, escaping embedded single quotes
// via the standard '\”-idiom so the result is safe to embed in a shell
// command string.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// Compile-time assertion: *Armer satisfies the engine.DeadmanArmer interface.
// The interface lives in internal/engine which we cannot import here
// (import cycle), so we assert the method set by signature matching instead.
var _ interface {
	Arm(context.Context, api.Transport, uuid.UUID, []api.PreState) (string, int64, error)
	Cancel(context.Context, api.Transport, uuid.UUID) error
} = (*Armer)(nil)
