// kensa agent wire protocol — v1.
//
// L-007 deliverable scaffolded Request/Response/Error/Heartbeat
// with opaque bytes payloads. L-009 replaces the bytes payloads
// with a typed `oneof` covering Apply / Capture / Rollback /
// Heartbeat. Founder ratified protobuf as the wire format
// 2026-05-11 (see ~/.claude/.../memory/l007_wire_protocol.md).
//
// **Versioning policy.** This package is import-path-versioned
// (internal/agent/wirev1). A v2 wire format lands as a parallel
// package (wirev2/), and a transition window has both packages
// importable so the controller can speak either while agents
// catch up. The `schema_version` field on each root message is
// the per-message version handshake L-012 will inspect.
//
// **Field-number convention (L-009 C-07).** Envelope fields
// occupy 1..9. Payload variants start at 10 with gaps of 1
// (10/11/12/13). Future variants (ListMechanisms,
// DetectCapabilities, etc.) use 20+ so the schema can extend
// without renumbering.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: internal/agent/wirev1/wire.proto

package wirev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request is one of the four wire-level root messages
// (controller → agent). The typed `oneof payload` replaces
// L-007's opaque `bytes payload`. Field numbers 1..9 are
// envelope; 10..19 are L-009 payload variants; 20+ are reserved
// for future variants (L-013 binary push, future ListMechanisms,
// etc.).
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CorrelationId uint64                 `protobuf:"varint,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_Apply
	//	*Request_Capture
	//	*Request_Rollback
	//	*Request_Heartbeat
	//	*Request_Handshake
	//	*Request_ArmDeadman
	//	*Request_CancelDeadman
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Request) GetCorrelationId() uint64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetApply() *ApplyRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Apply); ok {
			return x.Apply
		}
	}
	return nil
}

func (x *Request) GetCapture() *CaptureRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Capture); ok {
			return x.Capture
		}
	}
	return nil
}

func (x *Request) GetRollback() *RollbackRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Rollback); ok {
			return x.Rollback
		}
	}
	return nil
}

func (x *Request) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Request) GetHandshake() *HandshakeRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *Request) GetArmDeadman() *ArmDeadmanRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_ArmDeadman); ok {
			return x.ArmDeadman
		}
	}
	return nil
}

func (x *Request) GetCancelDeadman() *CancelDeadmanRequest {
	if x != nil {
		if x, ok := x.Payload.(*Request_CancelDeadman); ok {
			return x.CancelDeadman
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_Apply struct {
	Apply *ApplyRequest `protobuf:"bytes,10,opt,name=apply,proto3,oneof"`
}

type Request_Capture struct {
	Capture *CaptureRequest `protobuf:"bytes,11,opt,name=capture,proto3,oneof"`
}

type Request_Rollback struct {
	Rollback *RollbackRequest `protobuf:"bytes,12,opt,name=rollback,proto3,oneof"`
}

type Request_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,13,opt,name=heartbeat,proto3,oneof"`
}

type Request_Handshake struct {
	Handshake *HandshakeRequest `protobuf:"bytes,14,opt,name=handshake,proto3,oneof"` // L-012
}

type Request_ArmDeadman struct {
	ArmDeadman *ArmDeadmanRequest `protobuf:"bytes,20,opt,name=arm_deadman,json=armDeadman,proto3,oneof"` // D-005
}

type Request_CancelDeadman struct {
	CancelDeadman *CancelDeadmanRequest `protobuf:"bytes,21,opt,name=cancel_deadman,json=cancelDeadman,proto3,oneof"` // D-005
}

func (*Request_Apply) isRequest_Payload() {}

func (*Request_Capture) isRequest_Payload() {}

func (*Request_Rollback) isRequest_Payload() {}

func (*Request_Heartbeat) isRequest_Payload() {}

func (*Request_Handshake) isRequest_Payload() {}

func (*Request_ArmDeadman) isRequest_Payload() {}

func (*Request_CancelDeadman) isRequest_Payload() {}

// Response is the agent → controller acknowledgment. The
// payload variant MUST correspond to the Request's variant
// (Apply → ApplyResponse, etc.); the L-011 dispatcher enforces
// this. The Error field (envelope-level) carries failures the
// agent could not encode as a typed response (framing error
// surfaced inline, schema-version mismatch caught by L-012).
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CorrelationId uint64                 `protobuf:"varint,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_ApplyResp
	//	*Response_CaptureResp
	//	*Response_RollbackResp
	//	*Response_HeartbeatAck
	//	*Response_HandshakeAck
	//	*Response_ArmDeadmanResp
	//	*Response_CancelDeadmanResp
	Payload isResponse_Payload `protobuf_oneof:"payload"`
	// error at field 99 (well outside the envelope-fields range
	// 1..9) because errors are envelope-level and orthogonal to
	// the payload variant — a Response may carry both a typed
	// payload AND an error (handler ran partially), or just an
	// error (handler couldn't run at all).
	Error         *Error `protobuf:"bytes,99,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Response) GetCorrelationId() uint64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetApplyResp() *ApplyResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_ApplyResp); ok {
			return x.ApplyResp
		}
	}
	return nil
}

func (x *Response) GetCaptureResp() *CaptureResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_CaptureResp); ok {
			return x.CaptureResp
		}
	}
	return nil
}

func (x *Response) GetRollbackResp() *RollbackResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_RollbackResp); ok {
			return x.RollbackResp
		}
	}
	return nil
}

func (x *Response) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*Response_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *Response) GetHandshakeAck() *HandshakeAck {
	if x != nil {
		if x, ok := x.Payload.(*Response_HandshakeAck); ok {
			return x.HandshakeAck
		}
	}
	return nil
}

func (x *Response) GetArmDeadmanResp() *ArmDeadmanResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_ArmDeadmanResp); ok {
			return x.ArmDeadmanResp
		}
	}
	return nil
}

func (x *Response) GetCancelDeadmanResp() *CancelDeadmanResponse {
	if x != nil {
		if x, ok := x.Payload.(*Response_CancelDeadmanResp); ok {
			return x.CancelDeadmanResp
		}
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_ApplyResp struct {
	ApplyResp *ApplyResponse `protobuf:"bytes,10,opt,name=apply_resp,json=applyResp,proto3,oneof"`
}

type Response_CaptureResp struct {
	CaptureResp *CaptureResponse `protobuf:"bytes,11,opt,name=capture_resp,json=captureResp,proto3,oneof"`
}

type Response_RollbackResp struct {
	RollbackResp *RollbackResponse `protobuf:"bytes,12,opt,name=rollback_resp,json=rollbackResp,proto3,oneof"`
}

type Response_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,13,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type Response_HandshakeAck struct {
	HandshakeAck *HandshakeAck `protobuf:"bytes,14,opt,name=handshake_ack,json=handshakeAck,proto3,oneof"` // L-012
}

type Response_ArmDeadmanResp struct {
	ArmDeadmanResp *ArmDeadmanResponse `protobuf:"bytes,20,opt,name=arm_deadman_resp,json=armDeadmanResp,proto3,oneof"` // D-005
}

type Response_CancelDeadmanResp struct {
	CancelDeadmanResp *CancelDeadmanResponse `protobuf:"bytes,21,opt,name=cancel_deadman_resp,json=cancelDeadmanResp,proto3,oneof"` // D-005
}

func (*Response_ApplyResp) isResponse_Payload() {}

func (*Response_CaptureResp) isResponse_Payload() {}

func (*Response_RollbackResp) isResponse_Payload() {}

func (*Response_HeartbeatAck) isResponse_Payload() {}

func (*Response_HandshakeAck) isResponse_Payload() {}

func (*Response_ArmDeadmanResp) isResponse_Payload() {}

func (*Response_CancelDeadmanResp) isResponse_Payload() {}

// Error is the envelope-level failure envelope. Used when the
// agent cannot construct a typed Response (schema mismatch,
// internal panic, decode failure on Request). Per-handler
// failures are surfaced in the typed Response's success/detail
// fields, not here.
//
// `code` is a stable enum-as-string reserved for L-009 schema
// growth (e.g., "schema_mismatch", "panic_recovered",
// "decode_failed").
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

// Heartbeat (legacy, L-007 scaffolding). Retained for backward
// compatibility with code written against the L-007 placeholder;
// new code uses HeartbeatRequest / HeartbeatAck inside a
// Request/Response envelope.
type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion  uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Sequence       uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SentUnixMicros int64                  `protobuf:"varint,3,opt,name=sent_unix_micros,json=sentUnixMicros,proto3" json:"sent_unix_micros,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Heartbeat) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Heartbeat) GetSentUnixMicros() int64 {
	if x != nil {
		return x.SentUnixMicros
	}
	return 0
}

// ApplyRequest invokes a mechanism's Apply phase on the target.
//
//	mechanism: handler name from rule YAML (e.g., "file_content")
//	params:    handler-specific parameters as a protobuf Struct
//	           (built via wirev1.MapToStruct from api.Params)
//	pre_state: optional captured state for capturable handlers;
//	           nil for non-capturable mechanisms
type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mechanism     string                 `protobuf:"bytes,1,opt,name=mechanism,proto3" json:"mechanism,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	PreState      *WirePreState          `protobuf:"bytes,3,opt,name=pre_state,json=preState,proto3" json:"pre_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyRequest) GetMechanism() string {
	if x != nil {
		return x.Mechanism
	}
	return ""
}

func (x *ApplyRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ApplyRequest) GetPreState() *WirePreState {
	if x != nil {
		return x.PreState
	}
	return nil
}

// ApplyResponse carries the Apply outcome.
type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepResult    *WireStepResult        `protobuf:"bytes,1,opt,name=step_result,json=stepResult,proto3" json:"step_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyResponse) GetStepResult() *WireStepResult {
	if x != nil {
		return x.StepResult
	}
	return nil
}

// CaptureRequest invokes a mechanism's Capture phase.
type CaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mechanism     string                 `protobuf:"bytes,1,opt,name=mechanism,proto3" json:"mechanism,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{6}
}

func (x *CaptureRequest) GetMechanism() string {
	if x != nil {
		return x.Mechanism
	}
	return ""
}

func (x *CaptureRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

// CaptureResponse carries the captured pre-state.
type CaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreState      *WirePreState          `protobuf:"bytes,1,opt,name=pre_state,json=preState,proto3" json:"pre_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureResponse) Reset() {
	*x = CaptureResponse{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureResponse) ProtoMessage() {}

func (x *CaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureResponse.ProtoReflect.Descriptor instead.
func (*CaptureResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{7}
}

func (x *CaptureResponse) GetPreState() *WirePreState {
	if x != nil {
		return x.PreState
	}
	return nil
}

// RollbackRequest invokes Rollback against a previously-captured
// PreState.
type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreState      *WirePreState          `protobuf:"bytes,1,opt,name=pre_state,json=preState,proto3" json:"pre_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{8}
}

func (x *RollbackRequest) GetPreState() *WirePreState {
	if x != nil {
		return x.PreState
	}
	return nil
}

// RollbackResponse carries the rollback outcome.
type RollbackResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RollbackResult *WireRollbackResult    `protobuf:"bytes,1,opt,name=rollback_result,json=rollbackResult,proto3" json:"rollback_result,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{9}
}

func (x *RollbackResponse) GetRollbackResult() *WireRollbackResult {
	if x != nil {
		return x.RollbackResult
	}
	return nil
}

// HeartbeatRequest is the controller → agent liveness ping.
//
//	token: caller-chosen u64 the ack must echo verbatim so the
//	       controller can pair acks with outstanding pings
//	       (multiple in flight is allowed).
//	sent_unix_micros: advisory clock-skew info; deadman timing
//	       uses the controller's local clock, not the agent's
//	       (per spec C-06: a compromised agent's clock is not
//	       trustworthy).
type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          uint64                 `protobuf:"varint,1,opt,name=token,proto3" json:"token,omitempty"`
	SentUnixMicros int64                  `protobuf:"varint,2,opt,name=sent_unix_micros,json=sentUnixMicros,proto3" json:"sent_unix_micros,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatRequest) GetToken() uint64 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *HeartbeatRequest) GetSentUnixMicros() int64 {
	if x != nil {
		return x.SentUnixMicros
	}
	return 0
}

// HeartbeatAck echoes the token verbatim plus the agent's local
// clock at receipt-time (also advisory).
type HeartbeatAck struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Token              uint64                 `protobuf:"varint,1,opt,name=token,proto3" json:"token,omitempty"`
	ReceivedUnixMicros int64                  `protobuf:"varint,2,opt,name=received_unix_micros,json=receivedUnixMicros,proto3" json:"received_unix_micros,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatAck) GetToken() uint64 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *HeartbeatAck) GetReceivedUnixMicros() int64 {
	if x != nil {
		return x.ReceivedUnixMicros
	}
	return 0
}

// WireStepResult mirrors api.StepResult.
type WireStepResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepIndex     int32                  `protobuf:"varint,1,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	Mechanism     string                 `protobuf:"bytes,2,opt,name=mechanism,proto3" json:"mechanism,omitempty"`
	Capturable    bool                   `protobuf:"varint,3,opt,name=capturable,proto3" json:"capturable,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Detail        string                 `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	Stranded      bool                   `protobuf:"varint,6,opt,name=stranded,proto3" json:"stranded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireStepResult) Reset() {
	*x = WireStepResult{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireStepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireStepResult) ProtoMessage() {}

func (x *WireStepResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireStepResult.ProtoReflect.Descriptor instead.
func (*WireStepResult) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{12}
}

func (x *WireStepResult) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *WireStepResult) GetMechanism() string {
	if x != nil {
		return x.Mechanism
	}
	return ""
}

func (x *WireStepResult) GetCapturable() bool {
	if x != nil {
		return x.Capturable
	}
	return false
}

func (x *WireStepResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WireStepResult) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *WireStepResult) GetStranded() bool {
	if x != nil {
		return x.Stranded
	}
	return false
}

// WirePreState mirrors api.PreState. The `data` field carries
// the mechanism-specific map[string]any via
// google.protobuf.Struct (built via wirev1.MapToStruct).
type WirePreState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepIndex     int32                  `protobuf:"varint,1,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	Mechanism     string                 `protobuf:"bytes,2,opt,name=mechanism,proto3" json:"mechanism,omitempty"`
	Capturable    bool                   `protobuf:"varint,3,opt,name=capturable,proto3" json:"capturable,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	CapturedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WirePreState) Reset() {
	*x = WirePreState{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WirePreState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WirePreState) ProtoMessage() {}

func (x *WirePreState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WirePreState.ProtoReflect.Descriptor instead.
func (*WirePreState) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{13}
}

func (x *WirePreState) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *WirePreState) GetMechanism() string {
	if x != nil {
		return x.Mechanism
	}
	return ""
}

func (x *WirePreState) GetCapturable() bool {
	if x != nil {
		return x.Capturable
	}
	return false
}

func (x *WirePreState) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WirePreState) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

// WireRollbackResult mirrors api.RollbackResult.
type WireRollbackResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StepIndex      int32                  `protobuf:"varint,1,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	Mechanism      string                 `protobuf:"bytes,2,opt,name=mechanism,proto3" json:"mechanism,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Detail         string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	PartialRestore bool                   `protobuf:"varint,5,opt,name=partial_restore,json=partialRestore,proto3" json:"partial_restore,omitempty"`
	Source         string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	ExecutedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WireRollbackResult) Reset() {
	*x = WireRollbackResult{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireRollbackResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireRollbackResult) ProtoMessage() {}

func (x *WireRollbackResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireRollbackResult.ProtoReflect.Descriptor instead.
func (*WireRollbackResult) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{14}
}

func (x *WireRollbackResult) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *WireRollbackResult) GetMechanism() string {
	if x != nil {
		return x.Mechanism
	}
	return ""
}

func (x *WireRollbackResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WireRollbackResult) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *WireRollbackResult) GetPartialRestore() bool {
	if x != nil {
		return x.PartialRestore
	}
	return false
}

func (x *WireRollbackResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *WireRollbackResult) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

// HandshakeRequest is the controller's protocol-version
// declaration. Sent on session start; the agent's
// HandshakeAck either accepts (compatible) or rejects
// (major mismatch). Major bumps mark breaking-change wire
// protocol revisions; minor bumps are additive.
type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Build         string                 `protobuf:"bytes,3,opt,name=build,proto3" json:"build,omitempty"` // human-readable build identifier (e.g., "v1.0.0", "dev-abc123")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{15}
}

func (x *HandshakeRequest) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *HandshakeRequest) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *HandshakeRequest) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

// HandshakeAck reports the agent's protocol identity and
// whether the controller is compatible.
type HandshakeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Accepted      bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // populated only when accepted=false
	Build         string                 `protobuf:"bytes,5,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeAck) Reset() {
	*x = HandshakeAck{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeAck) ProtoMessage() {}

func (x *HandshakeAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeAck.ProtoReflect.Descriptor instead.
func (*HandshakeAck) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{16}
}

func (x *HandshakeAck) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *HandshakeAck) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *HandshakeAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HandshakeAck) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

// ArmDeadmanRequest asks the agent to spin up an in-process
// deadman: a goroutine running an eventloop over a timerfd
// (window_seconds), parent pidfd, and signalfd(SIGTERM). On
// any wakeup the goroutine executes rollback_commands via the
// agent's LocalTransport.
//
// Replaces the at(1) / systemd-run scheduler path used in
// direct-SSH mode. Agent-mode default per Q1.c ratification
// (2026-05-12).
type ArmDeadmanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// txn_id is the transaction UUID (canonical lower-case
	// hyphenated form) used to identify the armed deadman in a
	// subsequent CancelDeadmanRequest.
	TxnId string `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	// window_seconds is the deadline. Per deadman-timer spec
	// C-03 the engine sends >= 120 seconds in production.
	WindowSeconds int64 `protobuf:"varint,2,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	// rollback_commands are shell commands executed in reverse-
	// apply order on the agent's LocalTransport when the
	// deadman fires. Generated by the engine-side dry-run of
	// each capturable step's Rollback handler against a
	// recordingTransport.
	RollbackCommands []string `protobuf:"bytes,3,rep,name=rollback_commands,json=rollbackCommands,proto3" json:"rollback_commands,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ArmDeadmanRequest) Reset() {
	*x = ArmDeadmanRequest{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmDeadmanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmDeadmanRequest) ProtoMessage() {}

func (x *ArmDeadmanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmDeadmanRequest.ProtoReflect.Descriptor instead.
func (*ArmDeadmanRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{17}
}

func (x *ArmDeadmanRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *ArmDeadmanRequest) GetWindowSeconds() int64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *ArmDeadmanRequest) GetRollbackCommands() []string {
	if x != nil {
		return x.RollbackCommands
	}
	return nil
}

// ArmDeadmanResponse confirms the arm. fires_at is the
// agent's local-clock unix-seconds when the timer will fire
// in the absence of a Cancel. Informational only — the
// engine's local-clock is authoritative for transaction
// timing.
type ArmDeadmanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FiresAt       int64                  `protobuf:"varint,1,opt,name=fires_at,json=firesAt,proto3" json:"fires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmDeadmanResponse) Reset() {
	*x = ArmDeadmanResponse{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmDeadmanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmDeadmanResponse) ProtoMessage() {}

func (x *ArmDeadmanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmDeadmanResponse.ProtoReflect.Descriptor instead.
func (*ArmDeadmanResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{18}
}

func (x *ArmDeadmanResponse) GetFiresAt() int64 {
	if x != nil {
		return x.FiresAt
	}
	return 0
}

// CancelDeadmanRequest tears down a previously-armed deadman.
// The agent cancels the goroutine's context, releases the
// fds, and removes the txn_id from its activeArms map. After
// Cancel returns, the rollback will NOT fire for this
// transaction.
type CancelDeadmanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelDeadmanRequest) Reset() {
	*x = CancelDeadmanRequest{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelDeadmanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDeadmanRequest) ProtoMessage() {}

func (x *CancelDeadmanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDeadmanRequest.ProtoReflect.Descriptor instead.
func (*CancelDeadmanRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{19}
}

func (x *CancelDeadmanRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

// CancelDeadmanResponse confirms the cancel.
// was_active is true if the agent had an arm in flight for
// txn_id; false if the cancel was a no-op (no matching arm).
type CancelDeadmanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WasActive     bool                   `protobuf:"varint,1,opt,name=was_active,json=wasActive,proto3" json:"was_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelDeadmanResponse) Reset() {
	*x = CancelDeadmanResponse{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelDeadmanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDeadmanResponse) ProtoMessage() {}

func (x *CancelDeadmanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDeadmanResponse.ProtoReflect.Descriptor instead.
func (*CancelDeadmanResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{20}
}

func (x *CancelDeadmanResponse) GetWasActive() bool {
	if x != nil {
		return x.WasActive
	}
	return false
}

var File_internal_agent_wirev1_wire_proto protoreflect.FileDescriptor

const file_internal_agent_wirev1_wire_proto_rawDesc = "" +
	"\n" +
	" internal/agent/wirev1/wire.proto\x12\x12kensa.agent.wirev1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x04\n" +
	"\aRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\x04R\rcorrelationId\x128\n" +
	"\x05apply\x18\n" +
	" \x01(\v2 .kensa.agent.wirev1.ApplyRequestH\x00R\x05apply\x12>\n" +
	"\acapture\x18\v \x01(\v2\".kensa.agent.wirev1.CaptureRequestH\x00R\acapture\x12A\n" +
	"\brollback\x18\f \x01(\v2#.kensa.agent.wirev1.RollbackRequestH\x00R\brollback\x12D\n" +
	"\theartbeat\x18\r \x01(\v2$.kensa.agent.wirev1.HeartbeatRequestH\x00R\theartbeat\x12D\n" +
	"\thandshake\x18\x0e \x01(\v2$.kensa.agent.wirev1.HandshakeRequestH\x00R\thandshake\x12H\n" +
	"\varm_deadman\x18\x14 \x01(\v2%.kensa.agent.wirev1.ArmDeadmanRequestH\x00R\n" +
	"armDeadman\x12Q\n" +
	"\x0ecancel_deadman\x18\x15 \x01(\v2(.kensa.agent.wirev1.CancelDeadmanRequestH\x00R\rcancelDeadmanB\t\n" +
	"\apayloadJ\x04\b\x0f\x10\x14\"\xb8\x05\n" +
	"\bResponse\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\x04R\rcorrelationId\x12B\n" +
	"\n" +
	"apply_resp\x18\n" +
	" \x01(\v2!.kensa.agent.wirev1.ApplyResponseH\x00R\tapplyResp\x12H\n" +
	"\fcapture_resp\x18\v \x01(\v2#.kensa.agent.wirev1.CaptureResponseH\x00R\vcaptureResp\x12K\n" +
	"\rrollback_resp\x18\f \x01(\v2$.kensa.agent.wirev1.RollbackResponseH\x00R\frollbackResp\x12G\n" +
	"\rheartbeat_ack\x18\r \x01(\v2 .kensa.agent.wirev1.HeartbeatAckH\x00R\fheartbeatAck\x12G\n" +
	"\rhandshake_ack\x18\x0e \x01(\v2 .kensa.agent.wirev1.HandshakeAckH\x00R\fhandshakeAck\x12R\n" +
	"\x10arm_deadman_resp\x18\x14 \x01(\v2&.kensa.agent.wirev1.ArmDeadmanResponseH\x00R\x0earmDeadmanResp\x12[\n" +
	"\x13cancel_deadman_resp\x18\x15 \x01(\v2).kensa.agent.wirev1.CancelDeadmanResponseH\x00R\x11cancelDeadmanResp\x12/\n" +
	"\x05error\x18c \x01(\v2\x19.kensa.agent.wirev1.ErrorR\x05errorB\t\n" +
	"\apayloadJ\x04\b\x0f\x10\x14\"x\n" +
	"\x05Error\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\"x\n" +
	"\tHeartbeat\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12(\n" +
	"\x10sent_unix_micros\x18\x03 \x01(\x03R\x0esentUnixMicros\"\x9c\x01\n" +
	"\fApplyRequest\x12\x1c\n" +
	"\tmechanism\x18\x01 \x01(\tR\tmechanism\x12/\n" +
	"\x06params\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06params\x12=\n" +
	"\tpre_state\x18\x03 \x01(\v2 .kensa.agent.wirev1.WirePreStateR\bpreState\"T\n" +
	"\rApplyResponse\x12C\n" +
	"\vstep_result\x18\x01 \x01(\v2\".kensa.agent.wirev1.WireStepResultR\n" +
	"stepResult\"_\n" +
	"\x0eCaptureRequest\x12\x1c\n" +
	"\tmechanism\x18\x01 \x01(\tR\tmechanism\x12/\n" +
	"\x06params\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06params\"P\n" +
	"\x0fCaptureResponse\x12=\n" +
	"\tpre_state\x18\x01 \x01(\v2 .kensa.agent.wirev1.WirePreStateR\bpreState\"P\n" +
	"\x0fRollbackRequest\x12=\n" +
	"\tpre_state\x18\x01 \x01(\v2 .kensa.agent.wirev1.WirePreStateR\bpreState\"c\n" +
	"\x10RollbackResponse\x12O\n" +
	"\x0frollback_result\x18\x01 \x01(\v2&.kensa.agent.wirev1.WireRollbackResultR\x0erollbackResult\"R\n" +
	"\x10HeartbeatRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\x04R\x05token\x12(\n" +
	"\x10sent_unix_micros\x18\x02 \x01(\x03R\x0esentUnixMicros\"V\n" +
	"\fHeartbeatAck\x12\x14\n" +
	"\x05token\x18\x01 \x01(\x04R\x05token\x120\n" +
	"\x14received_unix_micros\x18\x02 \x01(\x03R\x12receivedUnixMicros\"\xbb\x01\n" +
	"\x0eWireStepResult\x12\x1d\n" +
	"\n" +
	"step_index\x18\x01 \x01(\x05R\tstepIndex\x12\x1c\n" +
	"\tmechanism\x18\x02 \x01(\tR\tmechanism\x12\x1e\n" +
	"\n" +
	"capturable\x18\x03 \x01(\bR\n" +
	"capturable\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\x12\x1a\n" +
	"\bstranded\x18\x06 \x01(\bR\bstranded\"\xd5\x01\n" +
	"\fWirePreState\x12\x1d\n" +
	"\n" +
	"step_index\x18\x01 \x01(\x05R\tstepIndex\x12\x1c\n" +
	"\tmechanism\x18\x02 \x01(\tR\tmechanism\x12\x1e\n" +
	"\n" +
	"capturable\x18\x03 \x01(\bR\n" +
	"capturable\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x12;\n" +
	"\vcaptured_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\"\x81\x02\n" +
	"\x12WireRollbackResult\x12\x1d\n" +
	"\n" +
	"step_index\x18\x01 \x01(\x05R\tstepIndex\x12\x1c\n" +
	"\tmechanism\x18\x02 \x01(\tR\tmechanism\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12'\n" +
	"\x0fpartial_restore\x18\x05 \x01(\bR\x0epartialRestore\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12;\n" +
	"\vexecuted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\"T\n" +
	"\x10HandshakeRequest\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\x12\x14\n" +
	"\x05build\x18\x03 \x01(\tR\x05build\"\x84\x01\n" +
	"\fHandshakeAck\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x14\n" +
	"\x05build\x18\x05 \x01(\tR\x05build\"~\n" +
	"\x11ArmDeadmanRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12%\n" +
	"\x0ewindow_seconds\x18\x02 \x01(\x03R\rwindowSeconds\x12+\n" +
	"\x11rollback_commands\x18\x03 \x03(\tR\x10rollbackCommands\"/\n" +
	"\x12ArmDeadmanResponse\x12\x19\n" +
	"\bfires_at\x18\x01 \x01(\x03R\afiresAt\"-\n" +
	"\x14CancelDeadmanRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\"6\n" +
	"\x15CancelDeadmanResponse\x12\x1d\n" +
	"\n" +
	"was_active\x18\x01 \x01(\bR\twasActiveB0Z.github.com/Hanalyx/kensa/internal/agent/wirev1b\x06proto3"

var (
	file_internal_agent_wirev1_wire_proto_rawDescOnce sync.Once
	file_internal_agent_wirev1_wire_proto_rawDescData []byte
)

func file_internal_agent_wirev1_wire_proto_rawDescGZIP() []byte {
	file_internal_agent_wirev1_wire_proto_rawDescOnce.Do(func() {
		file_internal_agent_wirev1_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_agent_wirev1_wire_proto_rawDesc), len(file_internal_agent_wirev1_wire_proto_rawDesc)))
	})
	return file_internal_agent_wirev1_wire_proto_rawDescData
}

var file_internal_agent_wirev1_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_internal_agent_wirev1_wire_proto_goTypes = []any{
	(*Request)(nil),               // 0: kensa.agent.wirev1.Request
	(*Response)(nil),              // 1: kensa.agent.wirev1.Response
	(*Error)(nil),                 // 2: kensa.agent.wirev1.Error
	(*Heartbeat)(nil),             // 3: kensa.agent.wirev1.Heartbeat
	(*ApplyRequest)(nil),          // 4: kensa.agent.wirev1.ApplyRequest
	(*ApplyResponse)(nil),         // 5: kensa.agent.wirev1.ApplyResponse
	(*CaptureRequest)(nil),        // 6: kensa.agent.wirev1.CaptureRequest
	(*CaptureResponse)(nil),       // 7: kensa.agent.wirev1.CaptureResponse
	(*RollbackRequest)(nil),       // 8: kensa.agent.wirev1.RollbackRequest
	(*RollbackResponse)(nil),      // 9: kensa.agent.wirev1.RollbackResponse
	(*HeartbeatRequest)(nil),      // 10: kensa.agent.wirev1.HeartbeatRequest
	(*HeartbeatAck)(nil),          // 11: kensa.agent.wirev1.HeartbeatAck
	(*WireStepResult)(nil),        // 12: kensa.agent.wirev1.WireStepResult
	(*WirePreState)(nil),          // 13: kensa.agent.wirev1.WirePreState
	(*WireRollbackResult)(nil),    // 14: kensa.agent.wirev1.WireRollbackResult
	(*HandshakeRequest)(nil),      // 15: kensa.agent.wirev1.HandshakeRequest
	(*HandshakeAck)(nil),          // 16: kensa.agent.wirev1.HandshakeAck
	(*ArmDeadmanRequest)(nil),     // 17: kensa.agent.wirev1.ArmDeadmanRequest
	(*ArmDeadmanResponse)(nil),    // 18: kensa.agent.wirev1.ArmDeadmanResponse
	(*CancelDeadmanRequest)(nil),  // 19: kensa.agent.wirev1.CancelDeadmanRequest
	(*CancelDeadmanResponse)(nil), // 20: kensa.agent.wirev1.CancelDeadmanResponse
	(*structpb.Struct)(nil),       // 21: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_internal_agent_wirev1_wire_proto_depIdxs = []int32{
	4,  // 0: kensa.agent.wirev1.Request.apply:type_name -> kensa.agent.wirev1.ApplyRequest
	6,  // 1: kensa.agent.wirev1.Request.capture:type_name -> kensa.agent.wirev1.CaptureRequest
	8,  // 2: kensa.agent.wirev1.Request.rollback:type_name -> kensa.agent.wirev1.RollbackRequest
	10, // 3: kensa.agent.wirev1.Request.heartbeat:type_name -> kensa.agent.wirev1.HeartbeatRequest
	15, // 4: kensa.agent.wirev1.Request.handshake:type_name -> kensa.agent.wirev1.HandshakeRequest
	17, // 5: kensa.agent.wirev1.Request.arm_deadman:type_name -> kensa.agent.wirev1.ArmDeadmanRequest
	19, // 6: kensa.agent.wirev1.Request.cancel_deadman:type_name -> kensa.agent.wirev1.CancelDeadmanRequest
	5,  // 7: kensa.agent.wirev1.Response.apply_resp:type_name -> kensa.agent.wirev1.ApplyResponse
	7,  // 8: kensa.agent.wirev1.Response.capture_resp:type_name -> kensa.agent.wirev1.CaptureResponse
	9,  // 9: kensa.agent.wirev1.Response.rollback_resp:type_name -> kensa.agent.wirev1.RollbackResponse
	11, // 10: kensa.agent.wirev1.Response.heartbeat_ack:type_name -> kensa.agent.wirev1.HeartbeatAck
	16, // 11: kensa.agent.wirev1.Response.handshake_ack:type_name -> kensa.agent.wirev1.HandshakeAck
	18, // 12: kensa.agent.wirev1.Response.arm_deadman_resp:type_name -> kensa.agent.wirev1.ArmDeadmanResponse
	20, // 13: kensa.agent.wirev1.Response.cancel_deadman_resp:type_name -> kensa.agent.wirev1.CancelDeadmanResponse
	2,  // 14: kensa.agent.wirev1.Response.error:type_name -> kensa.agent.wirev1.Error
	21, // 15: kensa.agent.wirev1.ApplyRequest.params:type_name -> google.protobuf.Struct
	13, // 16: kensa.agent.wirev1.ApplyRequest.pre_state:type_name -> kensa.agent.wirev1.WirePreState
	12, // 17: kensa.agent.wirev1.ApplyResponse.step_result:type_name -> kensa.agent.wirev1.WireStepResult
	21, // 18: kensa.agent.wirev1.CaptureRequest.params:type_name -> google.protobuf.Struct
	13, // 19: kensa.agent.wirev1.CaptureResponse.pre_state:type_name -> kensa.agent.wirev1.WirePreState
	13, // 20: kensa.agent.wirev1.RollbackRequest.pre_state:type_name -> kensa.agent.wirev1.WirePreState
	14, // 21: kensa.agent.wirev1.RollbackResponse.rollback_result:type_name -> kensa.agent.wirev1.WireRollbackResult
	21, // 22: kensa.agent.wirev1.WirePreState.data:type_name -> google.protobuf.Struct
	22, // 23: kensa.agent.wirev1.WirePreState.captured_at:type_name -> google.protobuf.Timestamp
	22, // 24: kensa.agent.wirev1.WireRollbackResult.executed_at:type_name -> google.protobuf.Timestamp
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_internal_agent_wirev1_wire_proto_init() }
func file_internal_agent_wirev1_wire_proto_init() {
	if File_internal_agent_wirev1_wire_proto != nil {
		return
	}
	file_internal_agent_wirev1_wire_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Apply)(nil),
		(*Request_Capture)(nil),
		(*Request_Rollback)(nil),
		(*Request_Heartbeat)(nil),
		(*Request_Handshake)(nil),
		(*Request_ArmDeadman)(nil),
		(*Request_CancelDeadman)(nil),
	}
	file_internal_agent_wirev1_wire_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_ApplyResp)(nil),
		(*Response_CaptureResp)(nil),
		(*Response_RollbackResp)(nil),
		(*Response_HeartbeatAck)(nil),
		(*Response_HandshakeAck)(nil),
		(*Response_ArmDeadmanResp)(nil),
		(*Response_CancelDeadmanResp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_agent_wirev1_wire_proto_rawDesc), len(file_internal_agent_wirev1_wire_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_agent_wirev1_wire_proto_goTypes,
		DependencyIndexes: file_internal_agent_wirev1_wire_proto_depIdxs,
		MessageInfos:      file_internal_agent_wirev1_wire_proto_msgTypes,
	}.Build()
	File_internal_agent_wirev1_wire_proto = out.File
	file_internal_agent_wirev1_wire_proto_goTypes = nil
	file_internal_agent_wirev1_wire_proto_depIdxs = nil
}
