// kensa agent wire protocol — v1 scaffolding.
//
// LL Phase 1 deliverable L-007. Founder ratified protobuf as the
// wire format 2026-05-11 (see ~/.claude/.../memory/l007_wire_protocol.md).
//
// L-007 ships the toolchain + four placeholder root message types.
// L-009 fills in the handler-invocation payload schema. Until then,
// payloads are opaque bytes so framing tests can round-trip without
// committing to a payload shape that's still being designed.
//
// Versioning policy: this package is import-path-versioned
// (internal/agent/wirev1). A v2 wire format lands as a parallel
// package (wirev2/), and a transition window has both packages
// importable so the controller can speak either while agents catch
// up. The `schema_version` field on each root message is the
// per-message version handshake L-012 will inspect.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: internal/agent/wirev1/wire.proto

package wirev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request is one of the four scaffolding root messages. At L-007 the
// payload is opaque bytes; L-009 will turn the bytes into a `oneof`
// of typed handler-invocation payloads (Apply, Capture, Rollback).
//
// Fields:
//
//	schema_version: pinned to 1 for L-007; L-012 reads this to detect
//	  controller↔agent skew.
//	correlation_id: caller-chosen u64. Responses carry the same id so
//	  the controller can match async responses back to their request.
//	payload: opaque bytes today; oneof at L-009.
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CorrelationId uint64                 `protobuf:"varint,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Request) GetCorrelationId() uint64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *Request) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Response is the agent→controller acknowledgment.
//
// Two payload variants will land in L-009 (success result, error).
// At L-007 the success/error split is represented by the `error`
// field being non-nil for failures.
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CorrelationId uint64                 `protobuf:"varint,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Response) GetCorrelationId() uint64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *Response) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Error is the typed failure-envelope.
//
// `code` is a stable enum reserved for L-009 — at L-007 we leave
// it as a string and let L-009 narrow to an enum once the failure
// taxonomy is settled.
//
// `detail` is human-readable, suitable for logging.
//
// `retryable` lets the controller decide whether to re-issue the
// request or surface the failure to the operator. The L-009 schema
// will tighten the contract; at L-007 it's advisory.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

// Heartbeat is the deadman-channel keepalive.
//
// The deadman travels on the same wire as Request/Response — L-010's
// framing carries a frame-type discriminator so the receiver can
// route heartbeats separately. At L-007 the message is minimal.
type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion  uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Sequence       uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SentUnixMicros int64                  `protobuf:"varint,3,opt,name=sent_unix_micros,json=sentUnixMicros,proto3" json:"sent_unix_micros,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_wirev1_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_agent_wirev1_wire_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Heartbeat) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Heartbeat) GetSentUnixMicros() int64 {
	if x != nil {
		return x.SentUnixMicros
	}
	return 0
}

var File_internal_agent_wirev1_wire_proto protoreflect.FileDescriptor

const file_internal_agent_wirev1_wire_proto_rawDesc = "" +
	"\n" +
	" internal/agent/wirev1/wire.proto\x12\x12kensa.agent.wirev1\"q\n" +
	"\aRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\x04R\rcorrelationId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xa3\x01\n" +
	"\bResponse\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\x04R\rcorrelationId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12/\n" +
	"\x05error\x18\x04 \x01(\v2\x19.kensa.agent.wirev1.ErrorR\x05error\"x\n" +
	"\x05Error\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\"x\n" +
	"\tHeartbeat\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12(\n" +
	"\x10sent_unix_micros\x18\x03 \x01(\x03R\x0esentUnixMicrosB3Z1github.com/Hanalyx/kensa-go/internal/agent/wirev1b\x06proto3"

var (
	file_internal_agent_wirev1_wire_proto_rawDescOnce sync.Once
	file_internal_agent_wirev1_wire_proto_rawDescData []byte
)

func file_internal_agent_wirev1_wire_proto_rawDescGZIP() []byte {
	file_internal_agent_wirev1_wire_proto_rawDescOnce.Do(func() {
		file_internal_agent_wirev1_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_agent_wirev1_wire_proto_rawDesc), len(file_internal_agent_wirev1_wire_proto_rawDesc)))
	})
	return file_internal_agent_wirev1_wire_proto_rawDescData
}

var file_internal_agent_wirev1_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_agent_wirev1_wire_proto_goTypes = []any{
	(*Request)(nil),   // 0: kensa.agent.wirev1.Request
	(*Response)(nil),  // 1: kensa.agent.wirev1.Response
	(*Error)(nil),     // 2: kensa.agent.wirev1.Error
	(*Heartbeat)(nil), // 3: kensa.agent.wirev1.Heartbeat
}
var file_internal_agent_wirev1_wire_proto_depIdxs = []int32{
	2, // 0: kensa.agent.wirev1.Response.error:type_name -> kensa.agent.wirev1.Error
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_agent_wirev1_wire_proto_init() }
func file_internal_agent_wirev1_wire_proto_init() {
	if File_internal_agent_wirev1_wire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_agent_wirev1_wire_proto_rawDesc), len(file_internal_agent_wirev1_wire_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_agent_wirev1_wire_proto_goTypes,
		DependencyIndexes: file_internal_agent_wirev1_wire_proto_depIdxs,
		MessageInfos:      file_internal_agent_wirev1_wire_proto_msgTypes,
	}.Build()
	File_internal_agent_wirev1_wire_proto = out.File
	file_internal_agent_wirev1_wire_proto_goTypes = nil
	file_internal_agent_wirev1_wire_proto_depIdxs = nil
}
